= の機能
:allow-uri-read: 




== の機能

Astra Control は、 Kubernetes アプリケーションデータのライフサイクル管理に不可欠な機能を提供

* 永続的ストレージを自動的に管理
* アプリケーション対応のオンデマンドの Snapshot とバックアップを作成
* ポリシーベースのスナップショットおよびバックアップ操作を自動化します
* NetApp SnapMirrorテクノロジを使用して、アプリケーションをリモートシステムにレプリケートします
* Kubernetes クラスタ間でアプリケーションとデータを移行
* 本番環境からステージング環境にアプリケーションを簡単にクローニングできます
* アプリケーションの稼働状態と保護状態を視覚化します
* バックアップと移行のワークフローを実装するには、ユーザインターフェイスまたは API を使用してください




== 導入モデル

Astra Control には、次の 2 つの導入モデルがあります。

* * Astra Control Service *：複数のクラウドプロバイダ環境でKubernetesクラスタのデータをアプリケーション対応で管理するネットアップマネージドサービス。
* * Astra Control Center * ：オンプレミス環境で実行される Kubernetes クラスタのアプリケーション対応データ管理を提供する、自己管理ソフトウェアです。


[cols="1h,2d,2a"]
|===
|  | Astra 制御サービス | Astra Control Center の略 


| どのような方法で提供されますか？ | ネットアップのフルマネージドクラウドサービス  a| 
ソフトウェアとしてダウンロード、インストール、および管理します



| ホストされているのはどこですか？ | ネットアップが選択したパブリッククラウドで実現  a| 
指定した Kubernetes クラスタで実行します



| 更新方法 | 管理はネットアップが行います  a| 
更新を管理します



| アプリケーションデータ管理機能とは何ですか？ | ストレージバックエンドと外部サービスを除く両方のプラットフォームで同じ機能を利用できます  a| 
ストレージバックエンドと外部サービスを除く両方のプラットフォームで同じ機能を利用できます



| ストレージバックエンドでサポートされるもの | ネットアップのクラウドサービス  a| 
* NetApp ONTAP AFF および FAS システム
* Cloud Volumes ONTAP ストレージバックエンド


|===


== Astra Control Service の仕組み

Astra Control Service は、常時稼働し、最新の機能で更新される、ネットアップが管理するクラウドサービスです。複数のコンポーネントを利用して、アプリケーションデータのライフサイクル管理を実現します。

Astra Control Service の概要は次のように機能します。

* Astra Control Service の利用を開始するには、クラウドプロバイダをセットアップし、 Astra アカウントに登録します。
+
** GKE クラスタでは、 Astra Control Service はを使用します https://cloud.netapp.com/cloud-volumes-service-for-gcp["NetApp Cloud Volumes Service for Google Cloud"^] または、永続ボリューム用のストレージバックエンドとして Google Persistent Disk を使用します。
** AKS クラスタの場合、 Astra Control Service はを使用します https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files の特長"^] または、永続ボリューム用のストレージバックエンドとしてAzureで管理されているディスクがあります。
** Amazon EKSクラスタの場合、Astra Control Serviceはを使用します https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^] または https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP 対応の Amazon FSX"^] 永続ボリュームのストレージバックエンドとして。


* 最初の Kubernetes コンピューティングを Astra Control サービスに追加します。Astra Control Service は、次の処理を実行します。
+
** バックアップコピーが格納されるクラウドプロバイダアカウントにオブジェクトストアを作成します。
+
Azure では、 Astra Control Service によって、 BLOB コンテナ用のリソースグループ、ストレージアカウント、およびキーも作成されます。

** クラスタに新しい admin ロールと Kubernetes サービスアカウントを作成します。
** 新しい admin ロールを使用してインストールします https://docs.netapp.com/us-en/trident/index.html["Astra Trident"^] をクリックして、 1 つ以上のストレージクラスを作成します。
** Azure NetApp Files または NetApp Cloud Volumes Service for Google Cloud をストレージバックエンドとして使用している場合、 Astra Control Service は Astra Trident を使用して、アプリケーション用の永続的ボリュームをプロビジョニングします。


* この時点で、アプリケーションをクラスタに追加できます。永続ボリュームは、新しいデフォルトのストレージクラスでプロビジョニングされます。
* 次に、 Astra Control Service を使用してこれらのアプリケーションを管理し、スナップショット、バックアップ、クローンの作成を開始します。


Astra Controlの無料プランを使用すると、最大10個のネームスペースをアカウントで管理できます。10以上を管理する場合は、無料プランからプレミアムプランにアップグレードして請求を設定する必要があります。



== Astra Control Center の仕組み

Astra Control Center は、お客様のプライベートクラウドでローカルに実行されます。

Astra Control Centerは、Tridentベースのストレージクラスを使用し、ONTAP 9.5以上のストレージバックエンドでKubernetesクラスタをサポートします。

クラウド接続環境では、 Cloud Insights を使用して高度なモニタリングとテレメトリを提供します。Cloud Insights 接続がない場合、 Astra Control Center では、限定的な（ 7 日間の指標）監視と計測データを使用できます。また、オープン指標エンドポイントを介して Kubernetes の標準の監視ツール（ Prometheus や Grafana など）にエクスポートすることもできます。

Astra Control Center は、 AutoSupport と Active IQ のエコシステムに完全に統合されており、ユーザとネットアップサポートにトラブルシューティングと使用に関する情報を提供します。

Astra Control Center を試用するには、 90 日間の評価版ライセンスを使用します。評価版は、Eメールとコミュニティオプションでサポートされています。また、製品内サポートダッシュボードから技術情報アーティクルやドキュメントにアクセスすることもできます。

Astra Control Center をインストールして使用するには、一定の要件を満たす必要があります https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html["要件"]。

Astra Control Center の概要は次のように機能します。

* Astra Control Center は、ローカル環境にインストールします。方法の詳細については、こちらをご覧ください https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html["Astra Control Center をインストールします"]。
* 次のようなセットアップタスクを実行したとします。
+
** ライセンスをセットアップする
** 最初のクラスタを追加します。
** クラスタを追加したときに検出されたストレージバックエンドを追加します。
** アプリケーションバックアップを格納するオブジェクトストアバケットを追加します。




方法の詳細については、こちらをご覧ください https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html["Astra Control Center をセットアップします"]。

クラスタにアプリケーションを追加できます。また、管理対象のクラスタにすでにアプリケーションがある場合は、Astra Control Centerを使用してそれらを管理できます。次に、Astra Control Centerを使用して、スナップショット、バックアップ、クローン、およびレプリケーション関係を作成します。



== を参照してください。

* https://docs.netapp.com/us-en/astra/index.html["Astra Control Service のマニュアル"^]
* https://docs.netapp.com/us-en/astra-control-center/index.html["Astra Control Center のドキュメント"^]
* https://docs.netapp.com/us-en/trident/index.html["Astra Trident のドキュメント"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API を使用"^]
* https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights のドキュメント"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP のドキュメント"^]

