---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: object storage, astra, buckets, s3, cr, custom resource 
summary: アプリケーションと永続的ストレージをバックアップする場合や、クラスタ間でアプリケーションのクローニングを行う場合は、オブジェクトストアバケットプロバイダの追加が不可欠です。 
---
= バケットを管理する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
アプリケーションや永続的ストレージをバックアップする場合や、クラスタ間でアプリケーションをクローニングする場合は、オブジェクトストアバケットプロバイダが不可欠です。Astra Control Center を使用して、オフクラスタのバックアップ先として、アプリケーションのオブジェクトストアプロバイダを追加します。

アプリケーション構成と永続的ストレージを同じクラスタにクローニングする場合、バケットは必要ありません。

次の Amazon Simple Storage Service （ S3 ）バケットプロバイダのいずれかを使用します。

* NetApp ONTAP S3
* NetApp StorageGRID S3 の略
* Microsoft Azure
* 汎用 S3
+

NOTE: Amazon Web Services（AWS）とGoogle Cloud Platform（GCP）では、汎用のS3バケットタイプを使用します。

+

NOTE: Astra Control CenterはAmazon S3を汎用のS3バケットプロバイダとしてサポートしていますが、Astra Control Centerは、AmazonのS3をサポートしていると主張するすべてのオブジェクトストアベンダーをサポートしているわけではありません。



バケットの状態は次のいずれかになります。

* Pending ：バケットの検出がスケジュールされています。
* Available ：バケットは使用可能です。
* Removed：バケットには現在アクセスできません。


Astra Control API を使用してバケットを管理する方法については、を参照してください link:https://docs.netapp.com/us-en/astra-automation/["Astra の自動化と API に関する情報"^]。

バケットの管理に関連して次のタスクを実行できます。

* link:../get-started/add-bucket.html["バケットを追加します"]
* <<バケットを編集する>>
* <<デフォルトバケットを設定する>>
* <<バケットのクレデンシャルをローテーションするか、削除する>>
* <<バケットを削除する>>
* link:["[Tech preview]カスタムリソースを使用したバケットの管理"]



NOTE: Astra Control Center の S3 バケットは、使用可能容量を報告しません。Astra Control Center で管理されているアプリケーションのバックアップまたはクローニングを行う前に、 ONTAP または StorageGRID 管理システムでバケット情報を確認します。



== バケットを編集する

バケットのアクセスクレデンシャル情報を変更したり、選択したバケットがデフォルトバケットかどうかを変更したりできます。


NOTE: バケットを追加するときは、正しいバケットプロバイダを選択し、そのプロバイダに適したクレデンシャルを指定します。たとえば、タイプとして NetApp ONTAP S3 が許可され、 StorageGRID クレデンシャルが受け入れられますが、このバケットを使用して原因の以降のアプリケーションのバックアップとリストアはすべて失敗します。を参照してください link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures["リリースノート"]。

.手順
. 左側のナビゲーションから、*バケット*を選択します。
. [*アクション*（* Actions *）]列のメニューから、[*編集（* Edit）]を選択します。
. バケットタイプ以外の情報を変更します。
+

TIP: バケットタイプは変更できません。

. 「 * Update * 」を選択します。




== デフォルトバケットを設定する

クラスタ間でクローニングを実行する場合、Astra Controlにはデフォルトバケットが必要です。すべてのクラスタにデフォルトバケットを設定するには、次の手順を実行します。

.手順
. 「* Cloud Instances *」に移動します。
. リスト内のクラウドインスタンスの*アクション*列でメニューを選択します。
. 「 * 編集 * 」を選択します。
. [* Bucket*]リストで、デフォルトにするバケットを選択します。
. [ 保存（ Save ） ] を選択します。




== バケットのクレデンシャルをローテーションするか、削除する

Astra Controlは、バケットのクレデンシャルを使用してS3バケットにアクセスし、シークレットキーを提供することで、Astra Control Centerがバケットと通信できるようにします。



=== バケットのクレデンシャルをローテーションする

クレデンシャルのローテーションを行う場合は、バックアップが進行中でないとき（スケジュール設定またはオンデマンド）に、ローテーションを継続して実行してください。

.クレデンシャルの編集やローテーションを行う手順
. 左側のナビゲーションから、*バケット*を選択します。
. [ * アクション * （ * Actions * ） ] 列の [ オプション（ Options ） ] メニューから、 [ * 編集（ * Edit ） ] を選択する。
. 新しいクレデンシャルを作成します。
. 「 * Update * 」を選択します。




=== バケットのクレデンシャルを削除する

バケットのクレデンシャルを削除するのは、新しいクレデンシャルがバケットに適用されている場合やバケットがアクティブに使用されなくなった場合だけにしてください。


TIP: Astra Control に追加する最初のクレデンシャルセットは、 Astra Control がバックアップバケットの認証にクレデンシャルを使用するため、常に使用されています。バケットがアクティブな状態で使用されている場合は、これらのクレデンシャルを削除しないでください。削除すると、バックアップが失敗してバックアップが使用できなくなります。


NOTE: アクティブなバケットクレデンシャルを削除する場合は、を参照してください https://kb.netapp.com/Cloud/Astra/Control/Deleting_active_S3_bucket_credentials_leads_to_spurious_500_errors_reported_in_the_UI["バケットのクレデンシャル削除のトラブルシューティング"]。

Astra Control APIを使用してS3クレデンシャルを削除する方法については、を参照してください link:https://docs.netapp.com/us-en/astra-automation/["Astra の自動化と API に関する情報"^]。



== バケットを削除する

使用されなくなったバケットや正常でないバケットを削除することができます。これは、オブジェクトストアの設定をシンプルかつ最新の状態に保つために役立ちます。

[NOTE]
====
* デフォルトバケットを削除することはできません。そのバケットを削除する場合は、最初に別のバケットをデフォルトとして選択します。
* バケットのクラウドプロバイダの保持期間が終了する前にWrite Once Read Many（WORM）バケットを削除することはできません。WORMバケットは、バケット名の横に「Locked」と表示されます。


====
* デフォルトバケットを削除することはできません。そのバケットを削除する場合は、最初に別のバケットをデフォルトとして選択します。


.作業を開始する前に
* 開始する前に、このバケットの実行中または完了済みのバックアップがないことを確認してください。
* アクティブな保護ポリシーでバケットが使用されていないことを確認する必要があります。


あれば続けることはできません。

.手順
. 左ナビゲーションから、 * バケット * を選択します。
. [ アクション * （ Actions * ） ] メニューから、 [ * 削除（ Remove ） ] を選択します。
+

NOTE: Astra Control を使用すると、最初にバケットを使用してバックアップを実行するスケジュールポリシーが存在せず、削除しようとしているバケットにアクティブなバックアップが存在しないようにすることができます。

. 「 remove 」と入力して操作を確認します。
. 「 * Yes 、 remove bucket * 」を選択します。




== [Tech preview]カスタムリソースを使用したバケットの管理

アプリケーションクラスタでAstra Controlのカスタムリソース（CR）を使用してバケットを追加できます。アプリケーションと永続的ストレージをバックアップする場合や、クラスタ間でアプリケーションのクローニングを行う場合は、オブジェクトストアバケットプロバイダの追加が不可欠です。Astra Control は、これらのバックアップまたはクローンを、定義したオブジェクトストアバケットに格納します。カスタムリソースメソッドを使用している場合、アプリケーションのスナップショット機能にはバケットが必要です。

アプリケーション構成と永続的ストレージを同じクラスタにクローニングする場合、Astra Controlにバケットを作成する必要はありません。

Astra ControlのバケットカスタムリソースはAppVaultと呼ばれます。このCRには、保護処理でバケットを使用するために必要な設定が含まれています。

.作業を開始する前に
* Astra Control Centerで管理されているクラスタから到達できるバケットを用意します。
* バケットのクレデンシャルがあることを確認します。
* バケットが次のいずれかのタイプであることを確認します。
+
** NetApp ONTAP S3
** NetApp StorageGRID S3 の略
** Microsoft Azure
** 汎用 S3





NOTE: Amazon Web Services（AWS）では、Generic S3バケットタイプが使用されます。


NOTE: Astra Control CenterはAmazon S3を汎用のS3バケットプロバイダとしてサポートしていますが、Astra Control Centerは、AmazonのS3をサポートしていると主張するすべてのオブジェクトストアベンダーをサポートしているわけではありません。

.手順
. カスタムリソース（CR）ファイルを作成し、という名前を付けます（例： `astra-appvault.yaml`）。
. 次の属性を設定します。
+
** * metadata.name*:_（必須）_ AppVaultカスタムリソースの名前。
** * spec.prefix *：_（オプション）_ AppVaultに保存されているすべてのエンティティの名前のプレフィックスが付いたパス。
** * spec.providerConfig*:_（必須）_指定されたプロバイダを使用してAppVaultにアクセスするために必要な設定を保存します。
** * spec.providerCredentials*:_(必須)_指定されたプロバイダを使用してAppVaultにアクセスするために必要なすべての資格情報への参照を保存します。
+
*** * spec.providerCredentials.valueFromSecret*:_（オプション）_は、クレデンシャル値がシークレットから取得される必要があることを示します。
+
**** * key *：_（valueFromSecretを使用する場合は必須）_選択するシークレットの有効なキー。
**** * name *：_（valueFromSecretを使用する場合は必須）_このフィールドの値を含むシークレットの名前。同じネームスペースになければなりません。




** * spec.providerType*:_（必須）_バックアップの提供元を決定します（例：NetApp ONTAP S3、Microsoft Azure）。
+
YAMLの例：

+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: AppVault
metadata:
  name: astra-appvault
spec:
  providerType: generic-s3
  providerConfig:
    path: testpath
    endpoint: 192.168.1.100:80
    bucketName: bucket1
    secure: "false"
  providerCredentials:
    accessKeyID:
      valueFromSecret:
        name: s3-creds
        key: accessKeyID
    secretAccessKey:
      valueFromSecret:
        name: s3-creds
        key: secretAccessKey
----


. データを入力した後、 `astra-appvault.yaml` 正しい値を持つファイルを作成し、CRを適用します。
+
[source, console]
----
kubectl apply -f astra-appvault.yaml -n astra-connector
----
+

NOTE: バケットを追加すると、デフォルトのバケットインジケータで1つのバケットがAstra Controlによってマークされます。最初に作成したバケットがデフォルトバケットになります。バケットを追加する際、あとでを選択できます link:../use/manage-buckets.html#set-the-default-bucket["別のデフォルトバケットを設定する"^]。





== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/astra-automation["Astra Control API を使用"^]

