---
sidebar: sidebar 
permalink: use/manage-remote-authentication.html 
keywords: enable ldap authentication, disable, ldap, authentication, configure, manage 
summary: Astra ControlシステムでLDAP認証を管理します。 
---
= リモート認証を管理する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
LDAPは、分散ディレクトリ情報にアクセスするための業界標準プロトコルであり、エンタープライズ認証に広く使用されています。Astra Control CenterをLDAPサーバーに接続して、選択したAstra Controlユーザーの認証を実行できます。

大まかには、AstraとLDAPを統合し、Astra ControlユーザおよびLDAP定義に対応するグループを定義することです。Astra Control APIまたはWeb UIを使用して、LDAP認証とLDAPユーザおよびグループを設定できます。


IMPORTANT: Astra Control Centerは、LDAPの「メール」属性でメールアドレスを使用して、リモートユーザーを検索し、追跡します。この属性は、ディレクトリ内のオプションのフィールドまたは空のフィールドです。Astra Control Centerに表示するリモートユーザの場合は、このフィールドにEメールアドレスが存在している必要があります。この電子メールアドレスは、Astra Control Centerのユーザー名として認証に使用されます。



== LDAPS認証用の証明書を追加します

LDAPサーバのプライベートTLS証明書を追加して、LDAPS接続を使用する際にAstra Control CenterがLDAPサーバで認証できるようにします。この処理は、1回だけ、またはインストールした証明書の有効期限が切れたときにのみ実行してください。

.手順
. 「*アカウント*」に移動します。
. ［*証明書*］タブを選択します。
. 「 * 追加」を選択します。
. をアップロードします `.pem` クリップボードからファイルの内容をファイルまたは貼り付けます。
. [*Trusted*]チェックボックスをオンにします。
. [証明書の追加]を選択します。




== リモート認証を有効にします

LDAP認証を有効にして、Astra ControlとリモートLDAPサーバ間の接続を設定できます。

.作業を開始する前に
LDAPSを使用する場合は、Astra Control CenterがLDAPサーバに対して認証できるように、Astra Control CenterにLDAPサーバのプライベートTLS証明書がインストールされていることを確認してください。を参照してください <<LDAPS認証用の証明書を追加します>> 手順については、を参照し

.手順
. 「*アカウント」>「接続」に移動します。
. [* Remote Authentication *（リモート認証*）]ペインで、設定メニューを選択します。
. 「 * 接続」を選択します。
. サーバのIPアドレス、ポート、および優先接続プロトコル（LDAPまたはLDAPS）を入力します。
+

NOTE: ベストプラクティスとして、LDAPサーバに接続するときはLDAPSを使用してください。LDAPSに接続する前に、LDAPサーバのプライベートTLS証明書をAstra Control Centerにインストールする必要があります。

. サービスアカウントのクレデンシャルをEメール形式で入力します（administrator@example.com）。Astra Controlは、LDAPサーバとの接続時にこれらのクレデンシャルを使用します。
. [*ユーザー一致*]セクションで、LDAPサーバーからユーザー情報を取得するときに使用するベースDNと適切なユーザー検索フィルタを入力します。
. ［*グループ一致*］セクションで、グループ検索ベースDNと適切なカスタムグループ検索フィルタを入力します。
+

NOTE: 正しいベース識別名（DN）と、* User Match *および* Group Match *の適切な検索フィルタを使用してください。ベースDNは、検索を開始するディレクトリツリーのレベルをAstra Controlに指示し、検索フィルタは、Astra Controlが検索するディレクトリツリーの部分を制限します。

. [ 送信 ] を選択します。


.結果
[*リモート認証*]ペインのステータスは、LDAPサーバーへの接続が確立されると、[*保留中*]になり、次に[*接続済み*]になります。



== リモート認証を無効にします

LDAPサーバへのアクティブな接続を一時的に無効にすることができます。


NOTE: LDAPサーバへの接続を無効にすると、すべての設定が保存され、Astra Controlに追加されたすべてのリモートユーザとリモートグループがそのLDAPサーバから保持されます。このLDAPサーバにいつでも再接続できます。

.手順
. 「*アカウント」>「接続」に移動します。
. [* Remote Authentication *（リモート認証*）]ペインで、設定メニューを選択します。
. [*Disable*] を選択します。


.結果
[* Remote Authentication *（リモート認証*）]ペインのステータスが[* Disabled（無効）]に変わります。すべてのリモート認証設定、リモートユーザ、およびリモートグループが維持され、いつでも接続を再度有効にすることができます。



== リモート認証の設定を編集します

LDAPサーバーへの接続を無効にした場合、または*リモート認証*ペインが「接続エラー」状態にある場合は、設定を編集できます。


NOTE: 「リモート認証」ペインが「無効」状態の場合、LDAPサーバのURLまたはIPアドレスを編集することはできません。必要です <<リモート認証を切断します>> 最初に。

.手順
. 「*アカウント」>「接続」に移動します。
. [* Remote Authentication *（リモート認証*）]ペインで、設定メニューを選択します。
. 「 * 編集 * 」を選択します。
. 必要な変更を行い、* Edit *を選択します。




== リモート認証を切断します

LDAPサーバから切断して、Astra Controlから構成設定を削除できます。


CAUTION: LDAPサーバから切断すると、そのLDAPサーバのすべての構成設定がAstra Controlから削除されるだけでなく、そのLDAPサーバから追加されたすべてのリモートユーザとリモートグループも削除されます。

.手順
. 「*アカウント」>「接続」に移動します。
. [* Remote Authentication *（リモート認証*）]ペインで、設定メニューを選択します。
. 「*切断*」を選択します。


.結果
「*リモート認証*」パネルのステータスが「*切断済み*」に変わります。リモート認証設定、リモートユーザ、およびリモートグループがAstra Controlから削除される。
