---
sidebar: sidebar 
permalink: use/manage-remote-users-groups.html 
keywords: import, import users, search, search users, groups, import groups 
summary: Astra Control CenterシステムでリモートLDAPユーザーとグループを管理します。 
---
= リモートユーザとリモートグループを管理します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra ControlシステムでLDAP認証を有効にしている場合は、LDAPユーザおよびグループを検索して、承認されたシステムのユーザに含めることができます。



== リモートユーザを追加します

アカウント所有者と管理者は、リモートユーザをAstra Controlに追加できます。


NOTE: 同じEメールアドレスのローカルユーザがシステムにすでに存在する場合は、リモートユーザを追加できません。ユーザをリモートユーザとして追加するには、最初にローカルユーザをシステムから削除してください。

.手順
. [*Account*（アカウント*）]領域に移動します。
. [*Users & groups]タブを選択します。
. ページの右端で、*リモートユーザー*を選択します。
. 「 * 追加」を選択します。
. 必要に応じて、ユーザのEメールアドレスを* Filter by email *フィールドに入力して、LDAPユーザを検索します。
. リストから1人以上のユーザを選択します。
. ユーザにロールを割り当てます。
+

NOTE: ユーザとユーザのグループに異なるロールを割り当てると、より権限の高いロールが優先されます。

. 必要に応じて、このユーザに1つ以上のネームスペースの制約を割り当て、*ロールを制約に制限*を選択して適用します。新しい名前空間制約を追加するには、*制約の追加*を選択します。
+

NOTE: ユーザにLDAPグループメンバーシップを使用して複数のロールを割り当てると、最も権限の高いロールの制約だけが有効になります。たとえば'ローカルビューアロールを持つユーザーがメンバーロールにバインドされた3つのグループを結合すると'メンバーロールからの制約の合計が有効になり'ビューアロールからの制約はすべて無視されます

. 「 * 追加」を選択します。


.結果
新しいユーザがリモートユーザのリストに表示されます。このリストでは、ユーザーに対するアクティブな拘束を表示したり、*アクション*メニューからユーザーを管理したりできます。



== リモートグループを追加します

複数のリモートユーザを一度に追加するには、アカウント所有者と管理者がリモートグループをAstra Controlに追加します。リモートグループを追加すると、そのグループ内のすべてのリモートユーザがAstra Controlに追加され、同じロールを継承します。

.手順
. [*Account*（アカウント*）]領域に移動します。
. [*Users & groups]タブを選択します。
. ページの右端で、*リモートグループ*を選択します。
. 「 * 追加」を選択します。
+
このウィンドウには、Astra Controlがディレクトリから取得したLDAPグループの共通名と識別名のリストが表示されます。

. 必要に応じて、「*共通名でフィルタ*」フィールドにグループの共通名を入力してLDAPグループを検索します。
. リストから1つ以上のグループを選択します。
. グループにロールを割り当てます。
+

NOTE: 選択したロールは、このグループのすべてのユーザに割り当てられます。ユーザとユーザのグループに異なるロールを割り当てると、より権限の高いロールが優先されます。

. 必要に応じて、このグループに1つ以上の名前空間制約を割り当て、*制約にロールを制限*を選択して適用します。新しい名前空間制約を追加するには、*制約の追加*を選択します。
+

NOTE: ユーザにLDAPグループメンバーシップを使用して複数のロールを割り当てると、最も権限の高いロールの制約だけが有効になります。たとえば'ローカルビューアロールを持つユーザーがメンバーロールにバインドされた3つのグループを結合すると'メンバーロールからの制約の合計が有効になり'ビューアロールからの制約はすべて無視されます

. 「 * 追加」を選択します。


.結果
新しいグループがリモートグループのリストに表示され、このグループ内のすべてのリモートユーザがリモートユーザのリストに表示されます。このリストでは、*アクション*メニューからグループの詳細を表示したり、グループを管理したりできます。
