---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: クラウドプロバイダのクレデンシャルをアカウントにいつでも追加、削除できます。Astra は、これらの資格情報を使用して、お客様に代わってリソースをプロビジョニングします。 
---
= クレデンシャルを追加および削除します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
ONTAP S3 、 OpenShift で管理される Kubernetes クラスタ、未管理の Kubernetes クラスタなどのローカルプライベートクラウドプロバイダのクレデンシャルを、お客様のアカウントにいつでも追加、削除できます。Astra Control Center は、これらのクレデンシャルを使用して、クラスタ上の Kubernetes クラスタとアプリケーションを検出し、ユーザに代わってリソースをプロビジョニングします。

Astra Control Center のすべてのユーザーが同じ資格情報セットを共有することに注意してください。



== クレデンシャルを追加する

クラスターの管理時に、 Astra Control Center に資格情報を追加できます。新しいクラスタを追加してクレデンシャルを追加する方法については、を参照してください link:../get-started/add-cluster.html["Kubernetes クラスタを追加"]。


NOTE: 独自のkubeconfigファイルを作成する場合は、その中に* 1つの*コンテキスト要素のみを定義する必要があります。を参照してください https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Kubernetes のドキュメント"^] kubeconfigファイルの作成については、を参照してください。



== クレデンシャルを削除する

アカウントからのクレデンシャルの削除はいつでも実行できます。クレデンシャルは、のあとに削除してください link:unmanage.html["関連するすべてのクラスタの管理を解除します"]。


NOTE: Astra Control Center は、 Astra Control Center の認証情報を使用してバックアップバケットに認証するため、 Astra Control Center に追加する最初の資格情報セットは常に使用されています。これらのクレデンシャルは削除しないことを推奨します。

.手順
. 「 * アカウント * 」を選択します。
. [*Credentials] タブを選択します。
. 削除するクレデンシャルの [ 状態 *] 列で [ オプション ] メニューを選択します。
. 「 * 削除」を選択します。
. 削除を確認するために「削除」と入力し、「はい」、「認証情報を削除」を選択します。


.結果
Astra Control Center は、アカウントから資格情報を削除します。
