---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: add users, edit users, remove users, delete users 
summary: ユーザーを Astra Control Center システムに追加し、システムにアクセスできなくなったユーザーを削除します。 
---
= ユーザを管理します
:hardbreaks:
:icons: font
:imagesdir: ../media/use/


Astra Control Center UI を使用して、 Astra Control Center インストールのユーザーを追加、削除、および編集できます。Astra の UI またはを使用できます https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] ユーザを管理するには、を実行



== ユーザを追加します

アカウント所有者と管理者は、 Astra Control Center のインストールにさらにユーザーを追加できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」をクリックします。
. [*Users*] タブを選択します。
. [ ユーザーの追加 ] を選択します。
. ユーザ名、 E メールアドレス、および一時パスワードを入力します。
+
ユーザは初回ログイン時にパスワードを変更する必要があります。

. 適切なシステム権限を持つユーザロールを選択します。
+
各ロールには次の権限があります。

+
** * Viewer * はリソースを表示できます。
** * メンバー * には、ビューア・ロールの権限があり、アプリやクラスタを管理できますが、アプリやクラスタの管理を解除したり、スナップショットやバックアップを削除することはできません。
** *Admin* にはメンバーの役割権限があり、 Owner 以外の他のユーザーを追加および削除できます。
** * Owner * には Admin ロールの権限があり、任意のユーザーアカウントを追加および削除できます。


. [ 追加（ Add ） ] をクリックします。




== パスワードを管理します

Astra Control Center では、ユーザーアカウントのパスワードを管理できます。



=== パスワードを変更します

ユーザアカウントのパスワードはいつでも変更できます。

.手順
. 画面の右上にあるユーザアイコンをクリックします。
. * プロファイル * を選択します。
. [* アクション * （ Actions * ） ] ドロップダウンリストをクリックし、 [ * パスワードの変更 * （ Change Password ） ] を選択します。
. パスワードの要件に準拠するパスワードを入力します。
. 確認のためパスワードをもう一度入力します。
. [ パスワードの変更 *] をクリックします。




=== 別のユーザーのパスワードをリセットします

アカウントに Admin ロールまたは Owner ロールの権限がある場合は、自分だけでなく他のユーザアカウントのパスワードもリセットできます。パスワードをリセットする場合は、ログイン時にユーザが変更しなければならない一時パスワードを割り当てます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」をクリックします。
. [* ユーザー * ] タブで、ユーザーの [ 状態 * ] 列のドロップダウンリストを選択します。
. 「 * パスワードのリセット * 」を選択します。
. パスワードの要件に適合する一時パスワードを入力します。
. 確認のためパスワードをもう一度入力します。
+

NOTE: 次回ユーザがログインすると、パスワードの変更を求めるプロンプトが表示されます。

. [* パスワードのリセット * ] をクリックします。




== ユーザーの役割を変更します

Owner ロールのユーザはすべてのユーザのロールを変更できますが、 Admin ロールのユーザは Admin 、 Member 、 Viewer のロールを持つユーザのロールを変更できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」をクリックします。
. [*Users*] タブで、ユーザーの [*Role] 列のドロップダウンリストを選択します。
. 新しいロールを選択し ' プロンプトが表示されたら ' ［ 役割の変更 ］ をクリックします


Astra Control Center は、選択した新しいロールに基づいてユーザーの権限を更新します。



== ユーザを削除します

所有者ロールまたは管理者ロールを持つユーザは、いつでもそのアカウントから他のユーザを削除できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」をクリックします。
. [* ユーザー * ] タブで、削除する各ユーザーの行のチェックボックスをオンにします。
. [ アクション * ] をクリックし、 [ ユーザー / 秒の削除 ] を選択します。
. プロンプトが表示されたら、「 remove 」という単語を入力して削除を確認し、「 * Yes 、 Remove User * 」をクリックします。


Astra Control Center は、アカウントからユーザーを削除します。
