---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: add users, edit users, remove users, delete users 
summary: ユーザーを Astra Control Center システムに追加し、システムにアクセスできなくなったユーザーを削除します。 
---
= ユーザを管理します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Astra Control UI を使用して、 Astra Control Center インストールのユーザーを招待、追加、削除、および編集できます。Astra Control UI またはを使用できます https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] ユーザを管理するには、を実行



== ユーザーを招待します

アカウント所有者と管理者は、 Astra Control Center に新しいユーザを招待できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*Users*] タブを選択します。
. [* ユーザーの招待 * ] を選択します。
. ユーザの名前と E メールアドレスを入力します。
. 適切なシステム権限を持つユーザロールを選択します。
+
各ロールには次の権限があります。

+
** * Viewer * はリソースを表示できます。
** メンバー * には、ビューア・ロールの権限があり、アプリとクラスタの管理、アプリの管理解除、スナップショットとバックアップの削除ができます。
** *Admin* にはメンバーの役割権限があり、 Owner 以外の他のユーザーを追加および削除できます。
** * Owner * には Admin ロールの権限があり、任意のユーザーアカウントを追加および削除できます。


. メンバーロールまたはビューアロールを持つユーザーに制約を追加するには、 * 制約へのロールの制限 * チェックボックスをオンにします。
+
制約の追加の詳細については、を参照してください link:manage-roles.html["ロールの管理"]。

. [* ユーザーを招待する * ] を選択します。
+
ユーザーは、 Astra Control Center に招待されたことを通知する電子メールを受信します。このメールには一時的なパスワードが含まれています。このパスワードは初回ログイン時に変更する必要があります。





== ユーザを追加します

アカウント所有者と管理者は、 Astra Control Center のインストールにさらにユーザーを追加できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*Users*] タブを選択します。
. [ ユーザーの追加 ] を選択します。
. ユーザ名、 E メールアドレス、および一時パスワードを入力します。
+
ユーザは初回ログイン時にパスワードを変更する必要があります。

. 適切なシステム権限を持つユーザロールを選択します。
+
各ロールには次の権限があります。

+
** * Viewer * はリソースを表示できます。
** メンバー * には、ビューア・ロールの権限があり、アプリとクラスタの管理、アプリの管理解除、スナップショットとバックアップの削除ができます。
** *Admin* にはメンバーの役割権限があり、 Owner 以外の他のユーザーを追加および削除できます。
** * Owner * には Admin ロールの権限があり、任意のユーザーアカウントを追加および削除できます。


. メンバーロールまたはビューアロールを持つユーザーに制約を追加するには、 * 制約へのロールの制限 * チェックボックスをオンにします。
+
制約の追加の詳細については、を参照してください link:manage-roles.html["ロールの管理"]。

. 「 * 追加」を選択します。




== パスワードを管理します

Astra Control Center では、ユーザーアカウントのパスワードを管理できます。



=== パスワードを変更します

ユーザアカウントのパスワードはいつでも変更できます。

.手順
. 画面の右上にあるユーザアイコンを選択します。
. * プロファイル * を選択します。
. [ * アクション * （ * Actions * ） ] 列の [ オプション（ Options ） ] メニューから、 [ * パスワードの変更 * （ * Change Password ） ] を選択します
. パスワードの要件に準拠するパスワードを入力します。
. 確認のためパスワードをもう一度入力します。
. 「 * パスワードの変更 * 」を選択します。




=== 別のユーザーのパスワードをリセットします

アカウントに Admin ロールまたは Owner ロールの権限がある場合は、自分だけでなく他のユーザアカウントのパスワードもリセットできます。パスワードをリセットする場合は、ログイン時にユーザが変更しなければならない一時パスワードを割り当てます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [* アクション * （ * Actions * ） ] ドロップダウンリストを選択します。
. 「 * パスワードのリセット * 」を選択します。
. パスワードの要件に適合する一時パスワードを入力します。
. 確認のためパスワードをもう一度入力します。
+

NOTE: 次回ユーザがログインするときに、パスワードの変更を求めるプロンプトが表示されます。

. 「 * パスワードのリセット * 」を選択します。




== ユーザーの役割を変更します

Owner ロールのユーザはすべてのユーザのロールを変更できますが、 Admin ロールのユーザは Admin 、 Member 、 Viewer のロールを持つユーザのロールを変更できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [* アクション * （ * Actions * ） ] ドロップダウンリストを選択します。
. [ 役割の編集 ] を選択します。
. 新しいロールを選択します。
. ロールに制約を適用するには、 * 制約へのロールの制限 * チェックボックスを有効にして、リストから制約を選択します。
+
拘束がない場合は、拘束を追加できます。詳細については、を参照してください link:manage-roles.html["ロールの管理"]。

. [* 確認 *] を選択します。


Astra Control Center は、選択した新しいロールに基づいてユーザーの権限を更新します。



== ユーザを削除します

所有者ロールまたは管理者ロールを持つユーザは、いつでもそのアカウントから他のユーザを削除できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [* ユーザー * ] タブで、削除する各ユーザーの行にあるチェックボックスをオンにします。
. [ * アクション * （ * Actions * ） ] 列の [ オプション（ Options ） ] メニューから、 [ * ユーザー / 秒を削除（ * Remove user/s * ） ] を選択する
. プロンプトが表示されたら、「 remove 」という単語を入力して削除を確認し、「 * Yes 、 Remove User * 」を選択します。


Astra Control Center は、アカウントからユーザーを削除します。
