---
sidebar: sidebar 
permalink: use/manage-local-users-and-roles.html 
keywords: add users, edit users, remove users, delete users, manage roles 
summary: Astra Control Centerシステムでユーザーと役割を管理します。 
---
= ローカルユーザとロールを管理します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control UIを使用して、Astra Control Centerインストールのユーザーを追加、削除、および編集できます。Astra Control UI またはを使用できます https://["Astra Control API"^] ユーザを管理するには、を実行

LDAPを使用して、選択したユーザの認証を実行することもできます。



== LDAP を使用する

LDAPは、分散ディレクトリ情報にアクセスするための業界標準プロトコルであり、エンタープライズ認証に広く使用されています。Astra Control CenterをLDAPサーバーに接続して、選択したAstra Controlユーザーの認証を実行できます。大まかには、AstraとLDAPを統合し、Astra ControlユーザおよびLDAP定義に対応するグループを定義することです。Astra Control APIまたはWeb UIを使用して、LDAP認証とLDAPユーザおよびグループを設定できます。詳細については、次のドキュメントを参照してください。

* https://["リモート認証とユーザーの管理には、Astra Control APIを使用します"^]
* link:manage-remote-users-groups.html["リモートユーザとリモートグループの管理には、Astra Control UIを使用します"]
* link:manage-remote-authentication.html["リモート認証を管理するには、Astra Control UIを使用します"]




== ユーザを追加します

アカウント所有者と管理者は、 Astra Control Center のインストールにさらにユーザーを追加できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*Users*] タブを選択します。
. [ ユーザーの追加 ] を選択します。
. ユーザ名、 E メールアドレス、および一時パスワードを入力します。
+
ユーザは初回ログイン時にパスワードを変更する必要があります。

. 適切なシステム権限を持つユーザロールを選択します。
+
各ロールには次の権限があります。

+
** * Viewer * はリソースを表示できます。
** メンバー * には、ビューア・ロールの権限があり、アプリとクラスタの管理、アプリの管理解除、スナップショットとバックアップの削除ができます。
** *Admin* にはメンバーの役割権限があり、 Owner 以外の他のユーザーを追加および削除できます。
** * Owner * には Admin ロールの権限があり、任意のユーザーアカウントを追加および削除できます。


. メンバーロールまたはビューアロールを持つユーザーに制約を追加するには、 * 制約へのロールの制限 * チェックボックスをオンにします。
+
制約の追加の詳細については、を参照してください link:manage-local-users-and-roles.html["ローカルユーザとロールを管理します"]。

. 「 * 追加」を選択します。




== パスワードを管理します

Astra Control Center では、ユーザーアカウントのパスワードを管理できます。



=== パスワードを変更します

ユーザアカウントのパスワードはいつでも変更できます。

.手順
. 画面の右上にあるユーザアイコンを選択します。
. * プロファイル * を選択します。
. [ * アクション * （ * Actions * ） ] 列の [ オプション（ Options ） ] メニューから、 [ * パスワードの変更 * （ * Change Password ） ] を選択します
. パスワードの要件に準拠するパスワードを入力します。
. 確認のためパスワードをもう一度入力します。
. 「 * パスワードの変更 * 」を選択します。




=== 別のユーザのパスワードをリセットします

アカウントに Admin ロールまたは Owner ロールの権限がある場合は、自分だけでなく他のユーザアカウントのパスワードもリセットできます。パスワードをリセットする場合は、ログイン時にユーザが変更しなければならない一時パスワードを割り当てます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [* アクション * （ * Actions * ） ] ドロップダウンリストを選択します。
. 「 * パスワードのリセット * 」を選択します。
. パスワードの要件に適合する一時パスワードを入力します。
. 確認のためパスワードをもう一度入力します。
+

NOTE: 次回ユーザがログインするときに、パスワードの変更を求めるプロンプトが表示されます。

. 「 * パスワードのリセット * 」を選択します。




== ユーザを削除します

所有者ロールまたは管理者ロールを持つユーザは、いつでもそのアカウントから他のユーザを削除できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [* ユーザー * ] タブで、削除する各ユーザーの行にあるチェックボックスをオンにします。
. [ * アクション * （ * Actions * ） ] 列の [ オプション（ Options ） ] メニューから、 [ * ユーザー / 秒を削除（ * Remove user/s * ） ] を選択する
. プロンプトが表示されたら、「 remove 」という単語を入力して削除を確認し、「 * Yes 、 Remove User * 」を選択します。


.結果
Astra Control Center は、アカウントからユーザーを削除します。



== ロールの管理

ロールを管理するには、ネームスペースの制約を追加し、ユーザロールをその制約に制限します。これにより、組織内のリソースへのアクセスを制御できます。Astra Control UI またはを使用できます https://["Astra Control API"^] をクリックしてください。



=== ロールに名前空間制約を追加します

管理者または所有者ユーザーは、メンバーまたはビューアーの役割に名前空間の制約を追加できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*Users*] タブを選択します。
. [ * アクション * （ * Actions * ） ] 列で、メンバーまたはビューアーの役割を持つユーザーのメニューボタンを選択します。
. [ 役割の編集 ] を選択します。
. [ ロールを制約に制限する *] チェックボックスをオンにします。
+
このチェックボックスは、メンバーロールまたはビューアロールでのみ使用できます。[*Role] ドロップダウン・リストから別のロールを選択できます

. [ * 制約の追加 * ] を選択します。
+
使用可能な制約の一覧は、ネームスペースまたはネームスペースラベルで確認できます。

. [ 制約タイプ * （ Constraint type * ） ] ドロップダウンリストで、ネームスペースの構成方法に応じて、 [* Kubernetes namespace] * または [* Kubernetes namespace label* ] を選択します。
. リストから 1 つ以上の名前空間またはラベルを選択して、それらの名前空間にロールを制限する制約を構成します。
. [* 確認 *] を選択します。
+
[ 役割の編集 *] ページには、この役割に選択した拘束のリストが表示されます。

. [* 確認 *] を選択します。
+
[*Account*] ページでは、 [*Role] 列のメンバまたはビューアの役割の制約を表示できます。




NOTE: 制約を追加せずに役割の制約を有効にし、 * 確認 * を選択すると、役割には完全な制限があると見なされます（役割は、名前空間に割り当てられているリソースへのアクセスを拒否されます）。



=== ロールから名前空間制約を削除します

管理者または所有者ユーザーは、役割から名前空間の制約を削除できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*Users*] タブを選択します。
. [ * アクション * （ * Actions * ） ] 列で、アクティブな拘束を持つメンバーまたはビューアーの役割を持つユーザーのメニューボタンを選択する。
. [ 役割の編集 ] を選択します。
+
* 役割の編集 * （ Edit role * ）ダイアログには、役割のアクティブな拘束が表示されます。

. 削除する拘束の右側にある * X * を選択します。
. [* 確認 *] を選択します。




== を参照してください。

* link:../concepts/user-roles-namespaces.html["ユーザロールとネームスペース"]

