---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: how to set up object storage in astra, how to set up astra buckets, s3, astra, setting up astra control, how to set up astra control center, kubernetes 
summary: アプリケーションと永続的ストレージをバックアップする場合や、クラスタ間でアプリケーションのクローニングを行う場合は、オブジェクトストアバケットプロバイダの追加が不可欠です。 
---
= バケットを管理する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


アプリケーションや永続的ストレージをバックアップする場合や、クラスタ間でアプリケーションをクローニングする場合は、オブジェクトストアバケットプロバイダが不可欠です。Astra Control Center を使用して、オフクラスタのバックアップ先として、アプリケーションのオブジェクトストアプロバイダを追加します。

アプリケーション構成と永続的ストレージを同じクラスタにクローニングする場合、バケットは必要ありません。

次の Amazon Simple Storage Service （ S3 ）バケットプロバイダのいずれかを使用します。

* NetApp ONTAP S3
* NetApp StorageGRID S3 の略
* 汎用 S3
* Microsoft Azure



NOTE: Astra Control Center は Amazon S3 を汎用 S3 バケットプロバイダとしてサポートしていますが、 Astra Control Center は Amazon の S3 サポートを要求するすべてのオブジェクトストアベンダーをサポートしているわけではありません。

バケットの状態は次のいずれかになります。

* Pending ：バケットの検出がスケジュールされています。
* Available ：バケットは使用可能です。
* Removed ：バケットには現在アクセスできません。


Astra Control API を使用してバケットを管理する方法については、を参照してください link:https://docs.netapp.com/us-en/astra-automation/["Astra の自動化と API に関する情報"^]。

バケットの管理に関連して次のタスクを実行できます。

* link:../get-started/setup_overview.html#add-a-bucket["バケットを追加します"]
* <<Edit a bucket>>
* <<Remove a bucket>>



NOTE: Astra Control Center の S3 バケットは、使用可能容量を報告しません。Astra Control Center で管理されているアプリケーションのバックアップまたはクローニングを行う前に、 ONTAP または StorageGRID 管理システムでバケット情報を確認します。



== クレデンシャルを削除する

Astra Control API を使用して、アカウントから S3 クレデンシャルをいつでも削除できます。

詳細については、を参照してください https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API を使用"^]。


TIP: Astra Control に追加する最初のクレデンシャルセットは、 Astra Control がバックアップバケットの認証にクレデンシャルを使用するため、常に使用されています。これらの資格情報は削除しないことをお勧めします。



== バケットを編集する

バケットのアクセスクレデンシャル情報を変更したり、選択したバケットがデフォルトバケットかどうかを変更したりできます。


NOTE: バケットを追加するときは、正しいバケットプロバイダを選択し、そのプロバイダに適したクレデンシャルを指定します。たとえば、タイプとして NetApp ONTAP S3 が許可され、 StorageGRID クレデンシャルが受け入れられますが、このバケットを使用して原因の以降のアプリケーションのバックアップとリストアはすべて失敗します。を参照してください link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures["リリースノート"]。

.手順
. 左ナビゲーションから、 * バケット * を選択します。
. [ * アクション * （ * Actions * ） ] 列の [ オプション（ Options ） ] メニューから、 [ * 編集（ * Edit ） ] を選択する。
. バケットタイプ以外の情報を変更します。
+

TIP: バケットタイプは変更できません。

. 「 * Update * 」を選択します。




== バケットを削除する

使用されなくなったバケットや正常でないバケットを削除することができます。これは、オブジェクトストアの設定をシンプルかつ最新の状態に保つために役立ちます。


NOTE: デフォルトバケットを削除することはできません。そのバケットを削除する場合は、最初に別のバケットをデフォルトとして選択します。

.必要なもの
* 開始する前に、このバケットの実行中または完了済みのバックアップがないことを確認してください。
* アクティブな保護ポリシーでバケットが使用されていないことを確認する必要があります。


ある場合は、続行できません。

.手順
. 左ナビゲーションから、 * バケット * を選択します。
. [ アクション * （ Actions * ） ] メニューから、 [ * 削除（ Remove ） ] を選択します。
+

NOTE: Astra Control を使用すると、最初にバケットを使用してバックアップを実行するスケジュールポリシーが存在せず、削除しようとしているバケットにアクティブなバックアップが存在しないようにすることができます。

. 「 remove 」と入力して操作を確認します。
. 「 * Yes 、 remove bucket * 」を選択します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API を使用"^]

