---
sidebar: sidebar 
permalink: use/manage-connections.html 
keywords: manage package, packages, install 
summary: Astra Control Centerにパッケージをアップロードしてインストールできます。 
---
= リポジトリ接続を管理します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


ソフトウェアパッケージのインストールイメージやアーティファクトの参照として使用するリポジトリをAstra Controlに接続できます。ソフトウェアパッケージをインポートすると、Astra Controlは、イメージリポジトリ内のインストールイメージと、アーティファクトリポジトリ内のバイナリおよびその他のアーティファクトを参照します。

.必要なもの
* Astra Control Center をインストールした Kubernetes クラスタ
* アクセス可能な稼働中のDockerリポジトリ
* アクセス可能なアーティファクトリポジトリ（Artifactoryなど）が実行されている必要があります




== Dockerイメージリポジトリを接続する

Dockerイメージリポジトリを接続して、Astraデータストアなどのパッケージインストールイメージを保持できます。パッケージをインストールすると、Astra Controlはイメージリポジトリからパッケージイメージファイルをインポートします。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*接続*（Connections *）]タブを選択します。
. 「* Docker Image Repository *」セクションで、右上のメニューを選択します。
. 「 * 接続」を選択します。
. リポジトリのURLとポートを追加します。
. リポジトリのクレデンシャルを入力します。
. 「 * 接続」を選択します。


リポジトリが接続されました。「* Docker Image Repository *」セクションに、リポジトリのステータスが「Connected」になっていることを確認します。



== Dockerイメージリポジトリの接続を解除する

不要になったDockerイメージリポジトリへの接続を削除できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*接続*（Connections *）]タブを選択します。
. 「* Docker Image Repository *」セクションで、右上のメニューを選択します。
. 「*切断*」を選択します。
. 「* Yes、disconnect Docker image repository *」を選択します。


リポジトリが切断されました。「* Docker Image Repository *」セクションには、リポジトリのステータスが「Disconnected」になっているはずです。



== アーティファクトリポジトリを接続します

アーティファクトリポジトリをソフトウェアパッケージのバイナリなどのホストアーティファクトに接続できます。パッケージをインストールすると、Astra Controlによって、ソフトウェアパッケージのアーティファクトがイメージリポジトリからインポートされます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*接続*（Connections *）]タブを選択します。
. [アーティファクトリポジトリ*]セクションで'右上のメニューを選択します
. 「 * 接続」を選択します。
. リポジトリのURLとポートを追加します。
. 認証が必要な場合は、*認証を使用*チェックボックスを有効にして、リポジトリのクレデンシャルを入力します。
. 「 * 接続」を選択します。


リポジトリが接続されました。[アーティファクトリポジトリ*]セクションで'リポジトリに[接続済み]ステータスが表示されるはずです



== アーティファクトリポジトリの接続を解除します

不要になったアーティファクトリポジトリへの接続を削除できます

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*接続*（Connections *）]タブを選択します。
. [アーティファクトリポジトリ*]セクションで'右上のメニューを選択します
. 「*切断*」を選択します。
. [はい]を選択し'アーティファクト・リポジトリを切断します*


リポジトリが切断されました。[アーティファクトリポジトリ*]セクションで'リポジトリに[接続済み]ステータスが表示されるはずです

[discrete]
== 詳細については、こちらをご覧ください

* link:manage-packages-acc.html["ソフトウェアパッケージを管理します"]

