---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore 
summary: Astra では、スナップショットまたはバックアップからアプリケーション構成と永続的ストレージをリストアできます。オブジェクトストアから永続的ストレージのバックアップが転送されるため、既存のバックアップからのリストアが最も高速に完了します。 
---
= アプリケーションのリストア
:hardbreaks:
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control Center では、スナップショットまたはバックアップからアプリケーションを復元できます。Astra Control UI またはを使用できます https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] アプリを復元するには、

データがオブジェクトストアから転送されるため、バックアップからのリストアには時間がかかることがあります。このため、既存の Snapshot から同じクラスタへのリストアは、他の方法よりも高速です。


NOTE: Helm を使用してアプリケーションを展開する場合、 Astra Control Center には Helm バージョン 3 が必要です。Helm 3 （または Helm 2 から Helm 3 にアップグレード）を使用して展開されたアプリケーションの管理とクローニングが完全にサポートされています。Helm 2 で展開されたアプリケーションはサポートされていません。


NOTE: 別のクラスタにリストアする場合は、同じ永続的ボリュームアクセスモード（ ReadWriteMany など）をクラスタで使用していることを確認してください。デスティネーションの永続ボリュームアクセスモードが異なると、リストア処理は失敗します。

[NOTE]
====
OpenShift クラスタでアプリケーションをホストするプロジェクトを作成すると、プロジェクト（または Kubernetes ネームスペース）に SecurityContext UID が割り当てられます。Astra Control Center でアプリケーションを保護し、 OpenShift でそのアプリケーションを別のクラスタまたはプロジェクトに移動できるようにするには、アプリケーションを任意の UID として実行できるようにポリシーを追加する必要があります。たとえば、次の OpenShift CLI コマンドは、 WordPress アプリケーションに適切なポリシーを付与します。

OC new-project ワードプレス ` OC adm policy add -scc to -group anyuid system: serviceaccounts:wordpress `OC adm policy add -scc to -user Privileged -z default-n wordpress

====
.手順
. 「 * アプリケーション」をクリックし、アプリケーションの名前をクリックします。
. [ * データ保護 * ] をクリックします。
. Snapshot からリストアする場合は、 * Snapshots * アイコンを選択したままにします。それ以外の場合は、「 * Backups * 」アイコンをクリックしてバックアップからリストアします。
. リストア元の Snapshot またはバックアップの * Actions * 列のドロップダウンリストをクリックします。
. ［ * アプリケーションの復元 * ］ をクリックします。
. * リストアの詳細 * ：リストアされたアプリの詳細を指定します。デフォルトでは、現在のクラスタとネームスペースが表示されます。これらの値をそのままにしておくと、アプリがインプレースで復元され、アプリは以前のバージョンのに戻ります。別のクラスタまたはネームスペースにリストアする場合は、これらの値を変更してください。
+
** アプリケーションの名前と名前空間を入力します。
** アプリケーションのデスティネーションクラスタを選択します。
** [* Review （レビュー） ] をクリックします




. * リストアの概要 * ：リストア操作の詳細を確認し、「 restore 」と入力して、 * Restore * をクリックします。


Astra Control Center は、指定した情報に基づいてアプリケーションを復元します。アプリケーションをインプレースでリストアした場合、既存の永続ボリュームの内容が、リストアしたアプリケーションの永続ボリュームの内容に置き換えられます。


NOTE: データ保護処理（クローン、バックアップ、リストア）が完了して永続ボリュームのサイズを変更したあと、新しいボリュームのサイズが UI に表示されるまでに最大 20 分かかります。データ保護処理にかかる時間は数分です。また、ストレージバックエンドの管理ソフトウェアを使用してボリュームサイズの変更を確認できます。
