---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Astra Control Center と Astra Control Center Operator を削除する方法について説明します。 
---
= Astra Control Center をアンインストールします
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
試用版からフルバージョンの製品にアップグレードする場合は、 Astra Control Center コンポーネントの削除が必要になることがあります。Astra Control Center と Astra Control Center Operator を削除するには、この手順で説明されているコマンドを順に実行します。

アンインストールに問題がある場合は、を参照してください <<アンインストールに関する問題のトラブルシューティング>>。

.作業を開始する前に
. link:../use/unmanage.html#unmanage-an-app["すべてのアプリケーションの管理を解除します"] クラスタ。
. link:../use/unmanage.html#unmanage-a-cluster["すべてのクラスタの管理を解除します"]。


.手順
. Astra Control Center を削除します。次のコマンド例は、デフォルトのインストールに基づいています。カスタム構成を作成した場合は、コマンドを変更します。
+
[listing]
----
kubectl delete -f astra_control_center.yaml -n netapp-acc
----
+
結果

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. を削除するには、次のコマンドを使用します `netapp-acc` （またはカスタム名）ネームスペース：
+
[listing]
----
kubectl delete ns [netapp-acc or custom namespace]
----
+
結果の例：

+
[listing]
----
namespace "netapp-acc" deleted
----
. Astra Control Center オペレータシステムコンポーネントを削除するには、次のコマンドを使用します。
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
結果

+
[listing]
----
namespace/netapp-acc-operator deleted
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io deleted
role.rbac.authorization.k8s.io/acc-operator-leader-election-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role deleted
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding deleted
configmap/acc-operator-manager-config deleted
service/acc-operator-controller-manager-metrics-service deleted
deployment.apps/acc-operator-controller-manager deleted
----




== アンインストールに関する問題のトラブルシューティング

Astra Control Center のアンインストールで発生した問題に対処するには、次の回避策を実行します。



=== Astra Control Center をアンインストールしても、管理対象クラスタで監視オペレータポッドがクリーンアップされない

Astra Control Center をアンインストールする前にクラスタの管理を解除していない場合は、次のコマンドを使用して、ネットアップ監視ネームスペースとネームスペース内のポッドを手動で削除できます。

.手順
. 削除 `acc-monitoring` エージェント：
+
[listing]
----
kubectl delete agents acc-monitoring -n netapp-monitoring
----
+
結果

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. ネームスペースを削除します。
+
[listing]
----
kubectl delete ns netapp-monitoring
----
+
結果

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. リソースの削除を確認します。
+
[listing]
----
kubectl get pods -n netapp-monitoring
----
+
結果

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. 監視エージェントが削除されたことを確認：
+
[listing]
----
kubectl get crd|grep agent
----
+
サンプル結果：

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. カスタムリソース定義（ CRD ）情報の削除：
+
[listing]
----
kubectl delete crds agents.monitoring.netapp.com
----
+
結果

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




=== Astra Control Center をアンインストールしても、 Traefik CRD をクリーンアップできない

Traefik CRD を手動で削除できます。CRD はグローバルリソースであり、削除するとクラスタ上の他のアプリケーションに影響を与える可能性があります。

.手順
. クラスタにインストールされている Traefik CRD を表示します。
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
応答

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
middlewaretcps.traefik.containo.us            2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. CRD を削除します。
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us middlewaretcps.traefik.containo.us
----




== 詳細については、こちらをご覧ください

* link:../release-notes/known-issues.html["アンインストールに関する既知の問題"]

