---
sidebar: sidebar 
permalink: use/unmanage.html 
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster, kubernetes, astra, astra control 
summary: 管理する必要がなくなったアプリケーションやコンピューティングを Astra Control から削除 
---
= アプリケーションとクラスタの管理を解除します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
管理する必要がなくなったアプリケーションやクラスタを Astra Control Center から削除します。



== アプリの管理を解除します

バックアップ、スナップショット、またはクローンを作成する必要がなくなったアプリケーションの管理を Astra Control Center から停止します。

アプリケーションの管理を解除すると、次のようになります。

* 既存のバックアップと Snapshot がすべて削除されます。
* アプリケーションとデータは引き続き使用できます。


.手順
. 左側のナビゲーションバーから、「 * アプリケーション * 」を選択します。
. アプリケーションを選択します。
. [アクション]列の[オプション]メニューから、*Unmanage*を選択します。
. 情報を確認します。
. 「 unmanage 」と入力して確定します。
. 「*はい、アプリケーションの管理を解除*」を選択します。


.結果
Astra Control Center がアプリケーションの管理を停止。



== クラスタの管理を解除します

管理する必要がなくなったクラスタをAstra Control Centerから管理しないようにします。


NOTE: クラスタの管理を解除する前に、クラスタに関連付けられているアプリケーションの管理を解除する必要があります。

クラスタの管理を解除する場合：

* この処理を実行すると、 Astra Control Center でクラスタが管理されなくなります。クラスタの構成は変更されず、クラスタも削除されません。
* Astra Trident はクラスタからアンインストールされません。 https://["Astra Trident のアンインストール方法をご確認ください"^]。


.手順
. 左側のナビゲーションバーから、 * クラスタ * を選択します。
. 管理する必要がなくなったクラスタのチェックボックスを選択します。
. * アクション * 列のオプションメニューから、 * 管理解除 * を選択します。
. クラスタの管理を解除することを確認し、「 * Yes 、 unmanage cluster * 」を選択します。


.結果
クラスタのステータスが「Removing *」に変わります。その後、クラスタが「*クラスタ」ページから削除され、Astra Control Centerによって管理されなくなります。


IMPORTANT: * Astra Control Center と Cloud Insights が接続されていない場合 * 、クラスタの管理を解除すると、テレメトリ・データの送信用にインストールされたすべてのリソースが削除されます。* Astra Control CenterとCloud Insights が接続されている場合*、クラスタの管理を解除すると、のみが削除されます `fluentbit` および `event-exporter` ポッド
