---
sidebar: sidebar 
permalink: use/upgrade-acc.html 
keywords: astra upgrade, upgrade astra control center, how to upgrade astra control, update 
summary: Astra Control Center をアップグレードするには、バンドルをダウンロードし、説明されている手順に従ってアップグレードします。 
---
= Astra Control Center をアップグレードします
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Centerをアップグレードするには、NetApp Support Site からインストールバンドルをダウンロードし、以下の手順を実行します。この手順を使用して、インターネット接続環境またはエアギャップ環境の Astra コントロールセンターをアップグレードできます。

.必要なもの
* アップグレードする前に、を参照してください link:../get-started/requirements.html#operational-environment-requirements["運用環境の要件"^] 環境がAstra Control Center導入の最小要件を満たしていることを確認する。環境に次の要素が必要です。
+
** サポートされているAstra Tridentバージョンで、実行しているバージョンを確認するには、既存のAstra Control Centerに対して次のコマンドを実行します。
+
[listing]
----
../../trident-installer/tridentctl -n trident version
----
+
を参照してください https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html#determine-the-version-to-upgrade-to["Astra Trident のドキュメント"] 古いバージョンからアップグレードするには、次の手順に従います。

+

WARNING: Kubernetes 1.25にアップグレードするには、Astra Trident 22.10 *にアップグレードする必要があります。

** サポートされているKubernetesディストリビューションで実行しているバージョンを確認するには、既存のAstra Control Centerに対して次のコマンドを実行します。 `kubectl get nodes -o wide`
** 十分なクラスタリソースを使用してクラスタリソースを確認し、既存のAstra Control Centerクラスタで次のコマンドを実行します。 `kubectl describe node <node name>`
** Astra Control Centerイメージのプッシュおよびアップロードに使用できるレジストリ
** デフォルトのストレージクラスデフォルトのストレージクラスを決定するには、既存のアストラコントロールセンターに対して次のコマンドを実行します。 `kubectl get storageclass`


* （OpenShiftのみ）すべてのクラスタオペレータが正常な状態であり、使用可能であることを確認します。
+
[listing]
----
kubectl get clusteroperators
----
* すべての API サービスが正常な状態であり、使用可能であることを確認します。
+
[listing]
----
kubectl get apiservices
----
* アップグレードを開始する前に、Astra Control Center UIからログアウトします。


Astra Control Center のアップグレードプロセスでは、次の手順を実行できます。

*  the Astra Control Center bundle
*  the bundle
*  the images to your local registry
*  the updated Astra Control Center operator
*  Astra Control Center
*  system status



IMPORTANT: Astra Control Centerオペレータ（たとえば、 `kubectl delete -f astra_control_center_operator_deploy.yaml`) Astra Control Centerのアップグレードまたは操作中はいつでもポッドを削除しないようにします。


TIP: スケジュール、バックアップ、 Snapshot が実行されていないときは、メンテナンス時間内にアップグレードを実行します。



== Astra Control Center バンドルをダウンロードします

. からAstra Control Centerバンドルをダウンロードします https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["ネットアップサポートサイト"^]。ファイル名は次のようになります。 `astra-control-center-[version].tar.gz`。
. （任意）バンドルのシグニチャを確認します。
+
[listing]
----
openssl dgst -sha256 -verify AstraControlCenter-public.pub -signature astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----




== バンドルを開梱します

. 画像を抽出します。
+
[listing]
----
tar -vxzf astra-control-center-[version].tar.gz
----




== NetApp Astra kubectlプラグインがインストールされていることを確認します

NetApp Astra kubectlコマンドラインプラグインは、Astra Control Centerの導入とアップグレードに関連する一般的なタスクを実行する際に時間を節約します。

. 次のコマンドを使用して、プラグインがインストールされているかどうかを確認します。
+
[listing]
----
kubectl astra
----


このコマンドはkubectlプラグインのヘルプを提供する必要があります。コマンドからエラーが返された場合は、次のコマンドを使用してプラグインをインストールします link:../get-started/install_acc.html#install-the-netapp-astra-kubectl-plugin["手順"]。



== イメージをローカルレジストリに追加します

. コンテナエンジンに応じた手順を実行します。


[role="tabbed-block"]
====
.Docker です
--
. をに変更します `acc` tarバンドルから抽出されたディレクトリ：
+
例



[listing]
----
cd ../acc
----
. Astra Control Centerのイメージディレクトリにあるパッケージイメージをローカルレジストリにプッシュします。コマンドを実行する前に、次の置き換えを行ってください。
+
** <BUNDLE_FILE> をAstra Controlバンドルファイルの名前に置き換えます (`acc.manifest.yaml`）。
** <MY_FULL_REGISTRY_PATH> をDockerリポジトリのURLに置き換えます。次に例を示します。 https://exampledownloads.jfrog.io/docker-astra-control/v1/[]。
** <MY_REGISTRY_USER> をユーザ名に置き換えます。
** <MY_REGISTRY_TOKEN> をレジストリの認証済みトークンに置き換えます。
+
[source, console]
----
kubectl astra packages push-images -m <BUNDLE_FILE> -r <MY_FULL_REGISTRY_PATH> -u <MY_REGISTRY_USER> -p <MY_REGISTRY_TOKEN>
----




--
.ポドマン
--
. レジストリにログインします。
+
[source, console]
----
podman login <MY_FULL_REGISTRY_PATH>
----
. 次のスクリプトを実行して、コメントに記載されているように<your _registry>を置き換えます。
+
[source, console]
----
# You need to be at the root of the tarball.
# You should see these files to confirm correct location:
#   acc.manifest.yaml
#   acc/

# Replace <YOUR_REGISTRY> with your own registry (e.g registry.customer.com or registry.customer.com/testing, etc..)
export REGISTRY=<YOUR_REGISTRY>
export PACKAGENAME=acc
export PACKAGEVERSION=22.11.0-82
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
  # Load to local cache
  astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')

  # Remove path and keep imageName.
  astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')

  # Tag with local image repo.
  podman tag ${astraImage} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}

  # Push to the local repo.
  podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----


--
====


== 更新された Astra Control Center オペレータをインストールします

. ディレクトリを変更します。
+
[listing]
----
cd manifests
----
. Astra Control Center オペレータの配備 YAML (`Astra_control_center_deployment.yaml ') を編集して、ローカルのレジストリと秘密を参照します。
+
[listing]
----
vim astra_control_center_operator_deploy.yaml
----
+
.. 認証が必要なレジストリを使用する場合は、のデフォルト行を置換または編集します `imagePullSecrets: []` 次の条件を満たす場合：
+
[listing]
----
imagePullSecrets:
- name: <astra-registry-cred_or_custom_name_of_secret>
----
.. 変更 `[your_registry_path]` をクリックします `kube-rbac-proxy` でイメージをプッシュしたレジストリパスへのイメージ  the images to your local registry,前の手順。
.. 変更 `[your_registry_path]` をクリックします `acc-operator` でイメージをプッシュしたレジストリパスへのイメージ  the images to your local registry,前の手順。
.. 「 env 」セクションに次の値を追加します。
+
[listing]
----
- name: ACCOP_HELM_UPGRADETIMEOUT
  value: 300m
----
+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *- name: ACCOP_HELM_UPGRADETIMEOUT*
          *value: 300m*
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      *imagePullSecrets: []*
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----


. 更新された Astra Control Center オペレータをインストールします。
+
[listing]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
回答例：

+
[listing]
----
namespace/netapp-acc-operator unchanged
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io configured
role.rbac.authorization.k8s.io/acc-operator-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role configured
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding configured
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding unchanged
configmap/acc-operator-manager-config unchanged
service/acc-operator-controller-manager-metrics-service unchanged
deployment.apps/acc-operator-controller-manager configured
----
. ポッドが実行中であることを確認します
+
[listing]
----
kubectl get pods -n netapp-acc-operator
----




== Astra Control Center をアップグレードします

. Astra Control Centerカスタムリソース（CR）を編集します。
+
[listing]
----
kubectl edit AstraControlCenter -n [netapp-acc or custom namespace]
----
. Astraのバージョン番号を変更します (`astraVersion` の内部 `Spec`）をアップグレードするバージョンにアップグレードします。
+
[listing, subs="+quotes"]
----
spec:
  accountName: "Example"
  *astraVersion: "[Version number]"*
----
. イメージレジストリパスが、イメージをでプッシュしたレジストリパスと一致することを確認します  the images to your local registry,前の手順。更新 `imageRegistry` の内部 `Spec` 前回のインストール以降にレジストリが変更されている場合。
+
[listing]
----
  imageRegistry:
    name: "[your_registry_path]"
----
. に次の項目を追加します `CRDs` の内部の設定 `Spec`：
+
[listing]
----
crds:
  shouldUpgrade: true
----
. Astra Control Center CR の 'Spec' の中にある 'additionalValues' 内に次の行を追加します
+
[listing]
----
additionalValues:
    nautilus:
      startupProbe:
        periodSeconds: 30
        failureThreshold: 600
----
+
ファイルエディタを保存して終了すると、変更が適用され、アップグレードが開始されます。

. （オプション）ポッドが終了し、再び使用可能になったことを確認します。
+
[listing]
----
watch kubectl get pods -n [netapp-acc or custom namespace]
----
. アップグレードが完了して準備完了になったことを示すために、Astraのステータス状態がになるまで待ちます (`True`）：
+
[listing]
----
kubectl get AstraControlCenter -n [netapp-acc or custom namespace]
----
+
対応：

+
[listing]
----
NAME    UUID                                      VERSION     ADDRESS         READY
astra   9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  22.11.0-24  10.111.111.111  True
----
+

NOTE: 処理中のアップグレードステータスを監視するには、次のコマンドを実行します。 `kubectl get AstraControlCenter -o yaml -n [netapp-acc or custom namespace]`

+

NOTE: Astra Control Centerのオペレータログを調べるには、次のコマンドを実行します。
`kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f`





== システムステータスを確認します

. Astra Control Center にログインします。
. バージョンがアップグレードされたことを確認します。UIの* Support *ページを参照してください。
. すべての管理対象クラスタとアプリケーションが引き続き存在し、保護されていることを確認します。

