---
sidebar: sidebar 
permalink: use/view-dashboard.html 
keywords: dashboard, cluster health, unhealthy apps, protected apps, discovered apps 
summary: ダッシュボードを選択すると、アプリケーション、コンピューティング、健全性の概要が表示されます。 
---
= アプリケーションとクラスタの健常性の概要を表示します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
ダッシュボード * を選択すると、アプリ、クラスター、ストレージバックエンド、それらのヘルスの概要が表示されます。

これらは静的な数値やステータスだけでなく、それぞれからドリルダウンすることもできます。たとえば、アプリが完全に保護されていない場合は、アイコンの上にカーソルを置くと、完全に保護されていないアプリを特定できます。その理由が含まれます。



== アプリケーションタイル

「 * アプリケーション * 」タイルは、次の項目を識別するのに役立ちます。

* Astra で現在管理しているアプリケーションの数。
* それらの管理アプリが正常であるかどうか。
* アプリケーションが完全に保護されているかどうか（最新のバックアップがある場合は保護されます）。
* 検出されたものの、まだ管理されていないアプリケーションの数。
+
アプリケーションが検出された後で管理または無視するため、この数はゼロになるのが理想的です。さらに、ダッシュボードで検出されたアプリケーションの数を監視して、開発者がクラスタに新しいアプリケーションを追加するタイミングを特定します。





== クラスタタイル

クラスタタイルには、 Astra Control Center を使用して管理しているクラスタの健常性に関する同様の詳細が表示され、ドリルダウンしてアプリと同様に詳細を確認できます。



== ストレージバックエンドはタイル張りです

「ストレージバックエンド * 」タイルは、ストレージバックエンドの健全性を特定するための情報を提供します。これには次のものが含まれます。

* 管理対象のストレージバックエンドの数
* これらの管理バックエンドが正常であるかどうか
* バックエンドが完全に保護されているかどうか
* 検出されたがまだ管理されていないバックエンドの数。

