---
sidebar: sidebar 
permalink: get-started/add-bucket.html 
keywords: set up astra control, add bucket 
summary: Astra Control Centerをインストールしたら、セットアップの一環としてバケットの追加を検討する必要があります。 
---
= バケットを追加します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
バケットは、Astra Control UIまたはを使用して追加できます https://docs.netapp.com/us-en/astra-automation["Astra Control API の略"^]。アプリケーションと永続的ストレージをバックアップする場合や、クラスタ間でアプリケーションのクローニングを行う場合は、オブジェクトストアバケットプロバイダの追加が不可欠です。Astra Control は、これらのバックアップまたはクローンを、定義したオブジェクトストアバケットに格納します。

アプリケーション構成と永続的ストレージを同じクラスタにクローニングする場合、Astra Controlにバケットを作成する必要はありません。アプリケーションのSnapshot機能にはバケットは必要ありません。

.作業を開始する前に
* Astra Control Centerで管理されているクラスタから到達できるバケットを用意します。
* バケットのクレデンシャルがあることを確認します。
* バケットが次のいずれかのタイプであることを確認します。
+
** NetApp ONTAP S3
** NetApp StorageGRID S3 の略
** Microsoft Azure
** 汎用 S3





NOTE: Amazon Web Services（AWS）とGoogle Cloud Platform（GCP）では、汎用のS3バケットタイプを使用します。


NOTE: Astra Control CenterはAmazon S3を汎用のS3バケットプロバイダとしてサポートしていますが、Astra Control Centerは、AmazonのS3をサポートしていると主張するすべてのオブジェクトストアベンダーをサポートしているわけではありません。

.手順
. 左側のナビゲーション領域で、 * バケット * を選択します。
. 「 * 追加」を選択します。
. バケットタイプを選択します。
+

NOTE: バケットを追加するときは、正しいバケットプロバイダを選択し、そのプロバイダに適したクレデンシャルを指定します。たとえば、タイプとして NetApp ONTAP S3 が許可され、 StorageGRID クレデンシャルが受け入れられますが、このバケットを使用して原因の以降のアプリケーションのバックアップとリストアはすべて失敗します。

. 既存のバケット名とオプションの概要 を入力します。
+

TIP: バケット名と概要 はバックアップ先として表示されるため、あとでバックアップを作成する際に選択できます。この名前は、保護ポリシーの設定時にも表示されます。

. S3 エンドポイントの名前または IP アドレスを入力します。
. [資格情報の選択*]で、[*追加*]または[*既存の*を使用]タブのいずれかを選択します。
+
** 「*追加」を選択した場合：
+
... Astra Control の他のクレデンシャルと区別するクレデンシャルの名前を入力します。
... クリップボードからコンテンツを貼り付けて、アクセス ID とシークレットキーを入力します。


** [既存の使用*]を選択した場合：
+
... バケットで使用する既存のクレデンシャルを選択します。




. 選択するオプション `Add`。
+

NOTE: バケットを追加すると、デフォルトのバケットインジケータで1つのバケットがAstra Controlによってマークされます。最初に作成したバケットがデフォルトバケットになります。バケットを追加する際、あとでを選択できます link:../use/manage-buckets.html#set-the-default-bucket["別のデフォルトバケットを設定する"]。


