---
sidebar: sidebar 
permalink: get-started/faq.html 
keywords: astra faq, astra frequently asked questions, what is astra, astra control, kubernetes, persistent volumes 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= Astra Control Center に関するよくある質問
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== 概要

次のセクションでは、 Astra Control Center を使用しているときに発生する可能性のあるその他の質問に対する回答を示します。詳しい説明については、 astra.feedback@netapp.com までお問い合わせください



== Astra Control Center へのアクセス

* Astra Control の URL は何であるか。 *

Astra Control Center は、ローカル認証と各環境に固有の URL を使用します。

URLには、ブラウザで、Astra Control Centerをインストールしたときに、Astra_control_center.yamlカスタムリソース（CR）ファイルのspec.astraatAddressフィールドに設定した完全修飾ドメイン名（FQDN）を入力します。emailは、Astra_control_center.yaml CRのspec.emailフィールドで設定した値です。



== ライセンス

*評価ライセンスを使用しています。フルライセンスに変更するにはどうすればよいですか?*

フルライセンスに変更するには、ネットアップからネットアップライセンスファイル（NLF）を入手します。

* 手順 *

. 左側のナビゲーションから、 * アカウント * > * ライセンス * を選択します。
. ライセンスの概要で、ライセンス情報の右側にある[Options]メニューを選択します。
. [置換]*を選択します。
. ダウンロードしたライセンスファイルを参照し、 * 追加 * を選択します。


*評価ライセンスを使用しています。アプリを管理できますか？ *

はい。評価ライセンス（デフォルトでインストールされている組み込み評価ライセンスを含む）を使用して、アプリケーションの管理機能をテストできます。評価用ライセンスとフルライセンスでは、機能や機能に違いはありません。評価用ライセンスは、単純に寿命が短くなります。を参照してください link:../concepts/licensing.html["ライセンス"^] を参照してください。



== Kubernetes クラスタを登録しています

* Astra Control に追加したワーカーノードを Kubernetes クラスタに追加する必要があります。どうすればよいですか？ *

新しいワーカーノードを既存のプールに追加できます。これらは Astra Control によって自動的に検出されます。新しいノードが Astra Control に表示されない場合は、新しいワーカーノードでサポートされているイメージタイプが実行されているかどうかを確認します。を使用して、新しいワーカーノードの健全性を確認することもできます `kubectl get nodes` コマンドを実行します

* クラスタの管理を適切に解除するにはどうすればよいですか *

. link:../use/unmanage.html["Astra Control からアプリケーションの管理を解除"]。
. link:../use/unmanage.html#stop-managing-compute["Astra Control からクラスタの管理を解除"]。


* Kubernetes クラスタを Astra Control から削除した後、アプリケーションとデータはどうなりますか。 *

Astra Control からクラスタを削除しても、クラスタの構成（アプリケーションと永続的ストレージ）は変更されません。このクラスタで作成されたアプリケーションの Snapshot やバックアップを Astra Control で復元することはできません。Astra Control で作成した永続的ストレージのバックアップは Astra Control に残っていますが、リストアには使用できません。


WARNING: 他の方法でクラスタを削除する場合は、必ず事前に Astra Control からクラスタを削除してください。Astra Control で管理している間に別のツールを使用してクラスタを削除した場合、原因で Astra Control アカウントに問題が発生する可能性があります。

* NetApp Astra Tridentの管理を解除すると、クラスタから自動的にアンインストールされますか？* Astra Control Centerでクラスタの管理を解除しても、Astra Tridentはクラスタから自動的にアンインストールされません。Astra Trident をアンインストールするには、が必要です https://["Astra Trident のドキュメントで次の手順を実行します"^]。



== アプリケーションの管理

* Astra Control はアプリケーションを導入できますか。 *

Astra Control はアプリケーションを導入しない。アプリケーションは Astra Control の外部に導入する必要があります。

* アプリケーションを Astra Control から管理しなくなった後、どうなりますか。 *

既存のバックアップまたは Snapshot がすべて削除されます。アプリケーションとデータは引き続き使用できます。管理対象外のアプリケーション、またはそのアプリケーションに属するバックアップや Snapshot では、データ管理操作を実行できません。

* ネットアップ以外のストレージにあるアプリケーションは Astra Control で管理できますか。 *

いいえネットアップ以外のストレージを使用しているアプリケーションは Astra Control で検出できますが、ネットアップ以外のストレージを使用しているアプリケーションは管理できません。

* Astra Control自体を管理する必要がありますか？*

いいえ。Astra Control自体は「システムアプリケーション」であるため、管理しないでください。

*不健全なポッドはアプリ管理に影響しますか？*

いいえ、ポッドの健全性はアプリ管理には影響しません。



== データ管理の操作

* アプリケーションは複数の PVS を使用しています。Astra ControlはこれらのPVSのスナップショットとバックアップを作成しますか*

はい。Astra Controlによるアプリケーションのスナップショット操作には、アプリケーションのPVCにバインドされているすべてのPVSのスナップショットが含まれます。

* Astra Control で取得したスナップショットを、別のインターフェイスやオブジェクトストレージから直接管理できますか。 *

いいえAstra Control で作成したスナップショットとバックアップは、 Astra Control でのみ管理できます。
