---
sidebar: sidebar 
permalink: get-started/install_acc.html 
keywords: astra installation, install astra control center, how to install astra control, deploy, download from netapp support 
summary: 環境に関するいくつかの前提条件に対処した後に Astra Control Center をインストールするには、バンドルをダウンロードして、説明されている手順に従ってインストールします。 
---
= 標準の手順で Astra Control Center をインストールします
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Centerをインストールするには、NetApp Support Site からインストールバンドルをダウンロードし、次の手順を実行します。この手順を使用して、インターネット接続環境またはエアギャップ環境に Astra コントロールセンターをインストールできます。

.その他のインストール手順
[%collapsible]
====
* * RedHat OpenShift OperatorHub *でのインストール：これを使用してください link:../get-started/acc_operatorhub_install.html["代替手順"] OperatorHubを使用してOpenShiftにAstra Control Centerをインストールするには、次の手順を実行します。
* * Cloud Volumes ONTAP バックエンドを使用してパブリッククラウドにインストール*：ユース link:../get-started/install_acc-cvo.html["これらの手順に従います"] Amazon Web Services（AWS）、Google Cloud Platform（GCP）、またはCloud Volumes ONTAP ストレージバックエンドを使用するMicrosoft AzureにAstra Control Centerをインストールするには、次の手順を実行します。


====
.必要なもの
* link:requirements.html["インストールを開始する前に、 Astra Control Center の導入環境を準備します"]。
* 使用環境でポッドセキュリティポリシーを設定または設定したい場合は、ポッドセキュリティポリシーと、それらがAstra Control Centerのインストールに与える影響について理解しておいてください。を参照してください link:../concepts/understand-pod-security.html["ポッドのセキュリティポリシーの制限事項を理解します"]。
* すべての API サービスが正常な状態であり、使用可能であることを確認します。
+
[source, console]
----
kubectl get apiservices
----
* 使用するネットアップFQDNがこのクラスタにルーティング可能であることを確認します。つまり、内部 DNS サーバに DNS エントリがあるか、すでに登録されているコア URL ルートを使用しています。
* クラスタにcert-managerがすでに存在する場合は、いくつかを実行する必要があります link:../get-started/cert-manager-prereqs.html["事前に必要な手順"] そのため、Astra Control Centerは独自のcert-managerをインストールしません。デフォルトでは、Astra Control Centerはインストール時に独自の証明書マネージャをインストールします。


.このタスクについて
Astra Control Centerのインストールプロセスでは、次の作業を行うことができます。

* にAstraコンポーネントを取り付けます `netapp-acc` （またはカスタム名）ネームスペース。
* デフォルトのAstra Control Owner管理者アカウントを作成します。
* 管理ユーザのEメールアドレスとデフォルトの初期セットアップパスワードを設定します。このユーザには、UIへの初回ログインに必要なオーナーロールが割り当てられます。
* Astra Control Centerのすべてのポッドが稼働していることを確認します。
* Astra Control Center UIをインストールします。



IMPORTANT: Astra Control Centerオペレータ（たとえば、 `kubectl delete -f astra_control_center_operator_deploy.yaml`) Astra Control Centerのインストール中または操作中はいつでも、ポッドを削除しないようにします。

.手順
Astra Control Center をインストールするには、次の手順に従います。

* <<Astra Control Centerをダウンロードして展開します>>
* <<ネットアップAstra kubectlプラグインをインストール>>
* <<イメージをローカルレジストリに追加します>>
* <<認証要件を持つレジストリのネームスペースとシークレットを設定します>>
* <<Astra Control Center オペレータを設置します>>
* <<Astra Control Center を設定します>>
* <<Astra Control Center とオペレータのインストールを完了します>>
* <<システムステータスを確認します>>
* <<ロードバランシング用の入力を設定します>>
* <<Astra Control Center UI にログインします>>




== Astra Control Centerをダウンロードして展開します

. にアクセスします https://mysupport.netapp.com/site/downloads/evaluation/astra-control-center["Astra Control Center評価ダウンロードページ"^] をクリックしますNetApp Support Site 。
. Astra Control Centerを含むバンドルをダウンロードします (`astra-control-center-[version].tar.gz`）。
. （推奨ですがオプション）Astra Control Centerの証明書と署名のバンドルをダウンロードします (`astra-control-center-certs-[version].tar.gz`）バンドルの署名を確認するには、次の手順を実行します。
+
[source, console]
----
tar -vxzf astra-control-center-certs-[version].tar.gz
----
+
[source, console]
----
openssl dgst -sha256 -verify certs/AstraControlCenter-public.pub -signature certs/astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----
+
出力にはと表示されます `Verified OK` 検証が成功したあとに、

. Astra Control Centerバンドルからイメージを抽出します。
+
[source, console]
----
tar -vxzf astra-control-center-[version].tar.gz
----




== ネットアップAstra kubectlプラグインをインストール

NetApp Astra kubectlコマンドラインプラグインは、Astra Control Centerの導入とアップグレードに関連する一般的なタスクを実行する際に時間を節約します。

.必要なもの
ネットアップでは、CPUアーキテクチャやオペレーティングシステム別にプラグインのバイナリを提供しています。このタスクを実行する前に、使用しているCPUとオペレーティングシステムを把握しておく必要があります。

.手順
. 使用可能なNetApp Astra kubectlプラグインのバイナリを表示し、オペレーティングシステムとCPUアーキテクチャに必要なファイルの名前をメモします。
+

NOTE: kubectlプラグインライブラリはtarバンドルの一部であり、フォルダに解凍されます `kubectl-astra`。

+
[source, console]
----
ls kubectl-astra/
----
. 正しいバイナリを現在のパスに移動し、名前をに変更します `kubectl-astra`：
+
[source, console]
----
cp kubectl-astra/<binary-name> /usr/local/bin/kubectl-astra
----




== イメージをローカルレジストリに追加します

. コンテナエンジンに応じた手順を実行します。


[role="tabbed-block"]
====
.Docker です
--
. tarballのルートディレクトリに移動します。次のファイルとディレクトリが表示されます。
+
`acc.manifest.bundle.yaml`
`acc/`

. Astra Control Centerのイメージディレクトリにあるパッケージイメージをローカルレジストリにプッシュします。を実行する前に、次の置換を行ってください `push-images` コマンドを実行します
+
** <BUNDLE_FILE> をAstra Controlバンドルファイルの名前に置き換えます (`acc.manifest.bundle.yaml`）。
** <MY_FULL_REGISTRY_PATH> をDockerリポジトリのURLに置き換えます。次に例を示します。 "https://<docker-registry>"[]。
** <MY_REGISTRY_USER> をユーザ名に置き換えます。
** <MY_REGISTRY_TOKEN> をレジストリの認証済みトークンに置き換えます。
+
[source, console]
----
kubectl astra packages push-images -m <BUNDLE_FILE> -r <MY_FULL_REGISTRY_PATH> -u <MY_REGISTRY_USER> -p <MY_REGISTRY_TOKEN>
----




--
.ポドマン
--
. tarballのルートディレクトリに移動します。次のファイルとディレクトリが表示されます。
+
`acc.manifest.bundle.yaml`
`acc/`

. レジストリにログインします。
+
[source, console]
----
podman login <YOUR_REGISTRY>
----
. 使用するPodmanのバージョンに合わせてカスタマイズされた次のいずれかのスクリプトを準備して実行します。<MY_FULL_REGISTRY_PATH> を'サブディレクトリを含むリポジトリのURLに置き換えます
+
[source, subs="specialcharacters,quotes"]
----
*Podman 4*
----
+
[source, console]
----
export REGISTRY=<MY_FULL_REGISTRY_PATH>
export PACKAGENAME=acc
export PACKAGEVERSION=22.11.0-82
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image: //')
astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')
podman tag ${astraImage} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----
+
[source, subs="specialcharacters,quotes"]
----
*Podman 3*
----
+
[source, console]
----
export REGISTRY=<MY_FULL_REGISTRY_PATH>
export PACKAGENAME=acc
export PACKAGEVERSION=22.11.0-82
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')
astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')
podman tag ${astraImage} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----
+

NOTE: レジストリ設定に応じて、スクリプトが作成するイメージパスは次のようになります。 `https://netappdownloads.jfrog.io/docker-astra-control-prod/netapp/astra/acc/22.11.0-82/image:version`



--
====


== 認証要件を持つレジストリのネームスペースとシークレットを設定します

. Astra Control Centerホストクラスタ用のKUBECONFIGをエクスポートします。
+
[source, console]
----
export KUBECONFIG=[file path]
----
+

NOTE: インストールを完了する前に、KUBECONFIGがAstra Control Centerをインストールするクラスタを指していることを確認してください。KUBECONFIGには、1つのコンテキストのみを含めることができます。

. 認証が必要なレジストリを使用する場合は、次の手順を実行する必要があります。
+
.. NetApp-acc-operator という名前空間を作成します。
+
[source, console]
----
kubectl create ns netapp-acc-operator
----
+
対応：

+
[listing]
----
namespace/netapp-acc-operator created
----
.. NetApp-acc-operator ネームスペースのシークレットを作成します。Docker 情報を追加して次のコマンドを実行します。
+

NOTE: プレースホルダ `your_registry_path` 以前にアップロードした画像の場所と一致する必要があります（例： `[Registry_URL]/netapp/astra/astracc/22.11.0-82`）。

+
[source, console]
----
kubectl create secret docker-registry astra-registry-cred -n netapp-acc-operator --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
回答例：

+
[listing]
----
secret/astra-registry-cred created
----
+

NOTE: シークレットの生成後にネームスペースを削除した場合は、ネームスペースを再作成し、ネームスペースのシークレットを再生成します。

.. を作成します `netapp-acc` （またはカスタム名）ネームスペース。
+
[source, console]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
回答例：

+
[listing]
----
namespace/netapp-acc created
----
.. のシークレットを作成します `netapp-acc` （またはカスタム名）ネームスペース。Docker 情報を追加して次のコマンドを実行します。
+
[source, console]
----
kubectl create secret docker-registry astra-registry-cred -n [netapp-acc or custom namespace] --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
応答

+
[listing]
----
secret/astra-registry-cred created
----






== Astra Control Center オペレータを設置します

. ディレクトリを変更します。
+
[source, console]
----
cd manifests
----
. Astra Control Center オペレータの配備 YAML (`Astra_control_center_deployment.yaml ') を編集して、ローカルのレジストリと秘密を参照します。
+
[source, console]
----
vim astra_control_center_operator_deploy.yaml
----
+

NOTE: 注釈付きサンプルYAMLは以下の手順に従います。

+
.. 認証が必要なレジストリを使用する場合は、デフォルト行の「 imagePullSecret:[] 」を次のように置き換えます。
+
[source, console]
----
imagePullSecrets:
- name: astra-registry-cred
----
.. 変更 `[your_registry_path]` をクリックします `kube-rbac-proxy` でイメージをプッシュしたレジストリパスへのイメージ <<イメージをローカルレジストリに追加します,前の手順>>。
.. 変更 `[your_registry_path]` をクリックします `acc-operator-controller-manager` でイメージをプッシュしたレジストリパスへのイメージ <<イメージをローカルレジストリに追加します,前の手順>>。
+
[source, subs="specialcharacters,quotes"]
----
*astra_control_center_operator_deploy.yaml*
----
+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        - name: ACCOP_HELM_INSTALLTIMEOUT
          value: 5m
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      *imagePullSecrets: []*
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----


. Astra Control Center オペレータをインストールします。
+
[source, console]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
回答例：

+
[listing]
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----
. ポッドが実行中であることを確認します
+
[source, console]
----
kubectl get pods -n netapp-acc-operator
----




== Astra Control Center を設定します

. Astra Control Centerカスタムリソース（CR）ファイルを編集します (`astra_control_center.yaml`)アカウント、AutoSupport 、レジストリ、およびその他の必要な設定を行うには、次の手順を実行します。
+
[source, console]
----
vim astra_control_center.yaml
----
+

NOTE: 注釈付きサンプルYAMLは以下の手順に従います。

. 次の設定を変更または確認します。
+
.アカウント名
[%collapsible]
====
|===
| 設定 | ガイダンス（Guidance） | を入力します | 例 


| アカウント名 | を変更します `accountName` stringには、Astra Control Centerアカウントに関連付ける名前を指定します。アカウント名は1つだけです。 | 文字列 | 例 
|===
====
+
.astraVersion
[%collapsible]
====
|===
| 設定 | ガイダンス（Guidance） | を入力します | 例 


| astraVersion | 導入するAstra Control Centerのバージョン。この設定には値があらかじめ入力されているため、対処は不要です。 | 文字列 | 22.11.1-82 
|===
====
+
.astraitAddress
[%collapsible]
====
|===
| 設定 | ガイダンス（Guidance） | を入力します | 例 


| astraitAddress | を変更します `astraAddress` ブラウザで使用するFQDN（推奨）またはIPアドレスを指定して、Astra Control Centerにアクセスします。このアドレスは、データセンターでAstra Control Centerがどのように検出されるかを定義します。このアドレスは、完了時にロードバランサからプロビジョニングしたFQDNまたはIPアドレスと同じです link:requirements.html["Astra Control Center の要件"^]。注：は使用しないでください `http://` または `https://` をクリックします。この FQDN をコピーしてで使用します <<Astra Control Center UI にログインします,後の手順>>。 | 文字列 | astra.example.com 
|===
====
+
.AutoSupport
[%collapsible]
====
このセクションで選択することで、ネットアップのプロアクティブサポートアプリケーション、NetApp Active IQ 、およびデータの送信先のどちらに参加するかが決まります。インターネット接続が必要です（ポート442）。サポートデータはすべて匿名化されます。

|===
| 設定 | 使用 | ガイダンス（Guidance） | を入力します | 例 


| AutoSupportに登録しました | または `enrolled` または `url` フィールドを選択する必要があります | 変更 `enrolled` を選択しますAutoSupport `false` インターネットに接続されていないか、または保持されているサイト `true` 接続されているサイト用。の設定 `true` 匿名データをネットアップに送信し、サポートを目的として使用できるようにします。デフォルトの選択はです `false` およびは、サポートデータがネットアップに送信されないことを示します。 | ブール値 | false（デフォルト値） 


| autosupport.urlに設定しました | または `enrolled` または `url` フィールドを選択する必要があります | このURLは匿名データの送信先を決定します。 | 文字列 | https://support.netapp.com/asupprod/post/1.0/postAsup[] 
|===
====
+
.E メール
[%collapsible]
====
|===
| 設定 | ガイダンス（Guidance） | を入力します | 例 


| E メール | を変更します `email` デフォルトの初期管理者アドレスを表す文字列。この E メールアドレスをコピーしてで使用します <<Astra Control Center UI にログインします,後の手順>>。このEメールアドレスは、最初のアカウントがUIにログインする際のユーザ名として使用され、Astra Controlのイベントが通知されます。 | 文字列 | admin@example.com 
|===
====
+
.FirstNameとLastName
[%collapsible]
====
|===
| 設定 | ガイダンス（Guidance） | を入力します | 例 


| FirstName | アストラアカウントに関連付けられている初期管理者の名前。ここで使用した名前は、初回ログイン後にUIの見出しに表示されます。 | 文字列 | SRE 


| 姓 | アストラアカウントに関連付けられている初期管理者の姓です。ここで使用した名前は、初回ログイン後にUIの見出しに表示されます。 | 文字列 | 管理 
|===
====
+
.imageRegistryのこと
[%collapsible]
====
このセクションで選択すると、Astraアプリケーションイメージ、Astra Control Center Operator、Astra Control Center Helmリポジトリをホストするコンテナイメージレジストリが定義されます。

|===
| 設定 | 使用 | ガイダンス（Guidance） | を入力します | 例 


| imageRegistry.name | 必須 | でイメージをプッシュしたイメージレジストリの名前 <<Astra Control Center オペレータを設置します,前の手順>>。使用しないでください `http://` または `https://` をレジストリ名に追加します。 | 文字列 | example.registry.com/astra 


| imageRegistry.secret | シークレットを必要とするimageRegistryを使用している場合は必須です。重要：認証を必要としないレジストリを使用している場合は、削除する必要があります `secret` ラインの内側 `imageRegistry` または、インストールが失敗します。 | イメージレジストリでの認証に使用するKubernetesシークレットの名前。 | 文字列 | Astra - registry-cred 
|===
====
+
.ストレージクラス
[%collapsible]
====
|===
| 設定 | ガイダンス（Guidance） | を入力します | 例 


| ストレージクラス | を変更します `storageClass` からの値 `ontap-gold` インストールに必要な別のTridentストレージクラスのリソースに移動します。コマンドを実行します `kubectl get sc` をクリックして、設定済みの既存のストレージクラスを確認します。Tridentベースのストレージクラスの1つをマニフェストファイル（Astra <version> マニフェスト）に入力する必要があり、Astra PVSに使用されます。設定されていない場合は、デフォルトのストレージクラスが使用されます。メモ：デフォルトのストレージクラスが設定されている場合は、デフォルトのアノテーションが設定されている唯一のストレージクラスであることを確認してください。 | 文字列 | ontap - goldの部分があります 
|===
====
+
.volumeReclaimPolicyのように指定します
[%collapsible]
====
|===
| 設定 | ガイダンス（Guidance） | を入力します | オプション（ Options ） 


| volumeReclaimPolicyのように指定します | これにより、AstraのPVSの再利用ポリシーが設定されます。このポリシーをに設定しています `Retain` Astraが削除されたあとに永続的なボリュームを保持このポリシーをに設定しています `Delete` Astraが削除されたあとに永続的ボリュームを削除する。この値が設定されていない場合、PVSは保持されます。 | 文字列  a| 
** 保持（デフォルト値）
** 削除


|===
====
+
.ingressType
[%collapsible]
====
|===
| 設定 | ガイダンス（Guidance） | を入力します | オプション（ Options ） 


| ingressType | 次の入力タイプのいずれかを使用します。* Generic * (`ingressType: "Generic"`）（デフォルト）別の入力コントローラを使用している場合、または独自の入力コントローラを使用する場合は、このオプションを使用します。Astra Control Centerを導入したら、を設定する必要があります link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["入力コントローラ"^] URLを使用してAstra Control Centerを公開します。* AccTraefik * (`ingressType: "AccTraefik"`）入力コントローラを設定しない場合は、このオプションを使用します。これにより、Astra Control Centerが導入されます `traefik` Gateway as a Kubernetes LoadBalancer type serviceの略。Astra Control Centerは、タイプ「LoadBalancer」のサービスを使用します。 (`svc/traefik` Astra Control Centerの名前空間）で、アクセス可能な外部IPアドレスが割り当てられている必要があります。お使いの環境でロードバランサが許可されていて、設定されていない場合は、MetalLBまたは別の外部サービスロードバランサを使用して外部IPアドレスをサービスに割り当てることができます。内部 DNS サーバ構成では、 Astra Control Center に選択した DNS 名を、負荷分散 IP アドレスに指定する必要があります。注：サービスタイプ「LoadBalancer」および入力の詳細については、を参照してください link:../get-started/requirements.html["要件"^]。 | 文字列  a| 
** 汎用（デフォルト値）
** AccTraefik社


|===
====
+
.astraitcesScaler
[%collapsible]
====
|===
| 設定 | ガイダンス（Guidance） | を入力します | オプション（ Options ） 


| astraitcesScaler | AstraeControlCenterリソース制限のスケーリングオプションデフォルトでは、Astra Control CenterはAstra内のほとんどのコンポーネントに対してリソース要求を設定して展開します。この構成により、アプリケーションの負荷と拡張性が高い環境では、Astra Control Centerソフトウェアスタックのパフォーマンスが向上します。ただし、小規模な開発またはテストクラスタを使用するシナリオでは、CRフィールドを使用します `astraResourcesScalar` に設定できます `Off`。これにより、リソース要求が無効になり、小規模なクラスタへの導入が可能になります。 | 文字列  a| 
** デフォルト（デフォルト値）
** オフ


|===
====
+
.CRD
[%collapsible]
====
このセクションで選択した内容によって、Astra Control CenterでのCRDの処理方法が決まります。

|===
| 設定 | ガイダンス（Guidance） | を入力します | 例 


| CRD.externalCertManagerの略 | 外部のcert-managerを使用する場合は、を変更します `externalCertManager` 終了： `true`。デフォルト `false` Astra Control Centerが、インストール時に独自の証明書マネージャCRDをインストールするようにします。SSDはクラスタ全体のオブジェクトであり、クラスタの他の部分に影響を及ぼす可能性があります。このフラグを使用すると、これらのCRDがAstra Control Centerの外部にあるクラスタ管理者によってインストールおよび管理されることをAstra Control Centerに伝えることができます。 | ブール値 | false（デフォルト値） 


| CRDs .externalTraefik | デフォルトでは、Astra Control Centerは必要なTraefik CRDをインストールします。SSDはクラスタ全体のオブジェクトであり、クラスタの他の部分に影響を及ぼす可能性があります。このフラグを使用すると、これらのCRDがAstra Control Centerの外部にあるクラスタ管理者によってインストールおよび管理されることをAstra Control Centerに伝えることができます。 | ブール値 | false（デフォルト値） 
|===
====


[source, subs="specialcharacters,quotes"]
----
*astra_control_center.yaml*
----
[listing, subs="+quotes"]
----
apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  accountName: "Example"
  astraVersion: "ASTRA_VERSION"
  astraAddress: "astra.example.com"
  autoSupport:
    enrolled: true
  email: "[admin@example.com]"
  firstName: "SRE"
  lastName: "Admin"
  imageRegistry:
    name: "[your_registry_path]"
    secret: "astra-registry-cred"
  storageClass: "ontap-gold"
  volumeReclaimPolicy: "Retain"
  ingressType: "Generic"
  astraResourcesScaler: "Default"
  additionalValues: {}
  crds:
    externalTraefik: false
    externalCertManager: false
----


== Astra Control Center とオペレータのインストールを完了します

. 前の手順で NetApp-acc` （またはカスタム）ネームスペースを作成していない場合は、次のようにします。
+
[source, console]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
回答例：

+
[listing]
----
namespace/netapp-acc created
----
. Astra Control Center を NetApp-acc' （またはカスタムの）名前空間にインストールします
+
[source, console]
----
kubectl apply -f astra_control_center.yaml -n [netapp-acc or custom namespace]
----
+
回答例：

+
[listing]
----
astracontrolcenter.astra.netapp.io/astra created
----




== システムステータスを確認します

kubectlコマンドを使用すると、システムステータスを確認できます。OpenShift を使用する場合は、同等の OC コマンドを検証手順に使用できます。

.手順
. すべてのシステムコンポーネントが正常にインストールされたことを確認します。
+
[source, console]
----
kubectl get pods -n [netapp-acc or custom namespace]
----
+
各ポッドのステータスは「 Running 」になります。システムポッドが展開されるまでに数分かかることがあります。

+
.回答例
[%collapsible]
====
[listing, subs="+quotes"]
----
NAME                                       READY   STATUS    RESTARTS        AGE
acc-helm-repo-76d8d845c9-ggds2             1/1     Running   0               14m
activity-6cc67ff9f4-z48mr                  1/1     Running   2 (8m32s ago)   9m
api-token-authentication-7s67v             1/1     Running   0               8m56s
api-token-authentication-bplb4             1/1     Running   0               8m56s
api-token-authentication-p2c9z             1/1     Running   0               8m56s
asup-6cdfbc6795-md8vn                      1/1     Running   0               9m14s
authentication-9477567db-8hnc9             1/1     Running   0               7m4s
bucketservice-f4dbdfcd6-wqzkw              1/1     Running   0               8m48s
cert-manager-bb756c7c4-wm2cv               1/1     Running   0               14m
cert-manager-cainjector-c9bb86786-8wrf5    1/1     Running   0               14m
cert-manager-webhook-dd465db99-j2w4x       1/1     Running   0               14m
certificates-68dff9cdd6-kcvml              1/1     Running   2 (8m43s ago)   9m2s
certificates-68dff9cdd6-rsnsb              1/1     Running   0               9m2s
cloud-extension-69d48c956c-2s8dt           1/1     Running   3 (8m43s ago)   9m24s
cloud-insights-service-7c4f48b978-7gvlh    1/1     Running   3 (8m50s ago)   9m28s
composite-compute-7d9ff5f68-nxbhl          1/1     Running   0               8m51s
composite-volume-57b4756d64-nl66d          1/1     Running   0               9m13s
credentials-6dbc55f89f-qpzff               1/1     Running   0               11m
entitlement-67bfb6d7-gl6kp                 1/1     Running   4 (8m33s ago)   9m38s
features-856cc4dccc-mxbdb                  1/1     Running   0               9m20s
fluent-bit-ds-4rtsp                        1/1     Running   0               6m54s
fluent-bit-ds-9rqll                        1/1     Running   0               6m54s
fluent-bit-ds-w5mp7                        1/1     Running   0               6m54s
graphql-server-7c7cc49776-jz2kn            1/1     Running   0               2m29s
identity-87c59c975-9jpnf                   1/1     Running   0               9m6s
influxdb2-0                                1/1     Running   0               13m
keycloak-operator-84ff6d59d4-qcnmc         1/1     Running   0               7m1s
krakend-cbf6c7df9-mdtzv                    1/1     Running   0               2m30s
license-5b888b78bf-plj6j                   1/1     Running   0               9m32s
login-ui-846b4664dd-fz8hv                  1/1     Running   0               2m24s
loki-0                                     1/1     Running   0               13m
metrics-facade-779cc9774-n26rw             1/1     Running   0               9m18s
monitoring-operator-974db78f-pkspq         2/2     Running   0               6m58s
nats-0                                     1/1     Running   0               13m
nats-1                                     1/1     Running   0               13m
nats-2                                     1/1     Running   0               13m
nautilus-7bdc7ddc54-49tfn                  1/1     Running   0               7m50s
nautilus-7bdc7ddc54-cwc79                  1/1     Running   0               9m36s
openapi-5584ff9f46-gbrdj                   1/1     Running   0               9m17s
openapi-5584ff9f46-z9mzk                   1/1     Running   0               9m17s
packages-bfc58cc98-lpxq9                   1/1     Running   0               8m58s
polaris-consul-consul-server-0             1/1     Running   0               13m
polaris-consul-consul-server-1             1/1     Running   0               13m
polaris-consul-consul-server-2             1/1     Running   0               13m
polaris-keycloak-0                         1/1     Running   3 (6m15s ago)   6m56s
polaris-keycloak-1                         1/1     Running   0               4m22s
polaris-keycloak-2                         1/1     Running   0               3m41s
polaris-keycloak-db-0                      1/1     Running   0               6m56s
polaris-keycloak-db-1                      1/1     Running   0               4m23s
polaris-keycloak-db-2                      1/1     Running   0               3m36s
polaris-mongodb-0                          2/2     Running   0               13m
polaris-mongodb-1                          2/2     Running   0               13m
polaris-mongodb-2                          2/2     Running   0               12m
polaris-ui-5ccff47897-8rzgh                1/1     Running   0               2m33s
polaris-vault-0                            1/1     Running   0               13m
polaris-vault-1                            1/1     Running   0               13m
polaris-vault-2                            1/1     Running   0               13m
public-metrics-6cb7bfc49b-p54xm            1/1     Running   1 (8m29s ago)   9m31s
storage-backend-metrics-5c77994586-kjn48   1/1     Running   0               8m52s
storage-provider-769fdc858c-62w54          1/1     Running   0               8m54s
task-service-9ffc484c5-kx9f4               1/1     Running   3 (8m44s ago)   9m34s
telegraf-ds-bphb9                          1/1     Running   0               6m54s
telegraf-ds-rtsm2                          1/1     Running   0               6m54s
telegraf-ds-s9h5h                          1/1     Running   0               6m54s
telegraf-rs-lbpv7                          1/1     Running   0               6m54s
telemetry-service-57cfb998db-zjx78         1/1     Running   1 (8m40s ago)   9m26s
tenancy-5d5dfbcf9f-vmbxh                   1/1     Running   0               9m5s
traefik-7b87c4c474-jmgp2                   1/1     Running   0               2m24s
traefik-7b87c4c474-t9k8x                   1/1     Running   0               2m24s
trident-svc-c78f5b6bd-nwdsq                1/1     Running   0               9m22s
vault-controller-55bbc96668-c6425          1/1     Running   0               11m
vault-controller-55bbc96668-lq9n9          1/1     Running   0               11m
vault-controller-55bbc96668-rfkgg          1/1     Running   0               11m
----
====
. （オプション）インストールが完了したことを確認するには、次のコマンドを使用して「 acc-operator' 」ログを監視します。
+
[source, console]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
+

NOTE: `accHost` クラスタの登録は最後の処理の1つです。登録に失敗しても原因 の導入は失敗しません。ログにクラスタ登録エラーが記録されている場合は、を使用して再度登録を試行できます link:../get-started/setup_overview.html#add-cluster["UIでクラスタワークフローを追加します"] または API 。

. すべてのポッドが実行中の場合は、インストールが正常に完了したことを確認します (`READY` はです `True`）を使用して、Astra Control Centerにログインするときに使用する初期セットアップパスワードを取得します。
+
[source, console]
----
kubectl get AstraControlCenter -n [netapp-acc or custom namespace]
----
+
対応：

+
[listing]
----
NAME    UUID                                  VERSION     ADDRESS         READY
astra   9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  22.11.0-82  10.111.111.111  True
----
+

IMPORTANT: UUIDの値をコピーします。パスワードは「 ACC-` 」の後に UUID 値（「 ACC-[UUID] 」）、またはこの例では「 ACC-9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f 」）です。





== ロードバランシング用の入力を設定します

サービスへの外部アクセスを管理するKubernetes入力コントローラを設定できます。これらの手順では、デフォルトのを使用した場合の入力コントローラの設定例を示します `ingressType: "Generic"` Astra Control Centerのカスタムリソース (`astra_control_center.yaml`）。を指定した場合、この手順 を使用する必要はありません `ingressType: "AccTraefik"` Astra Control Centerのカスタムリソース (`astra_control_center.yaml`）。

Astra Control Center を展開したら、 Astra Control Center を URL で公開するように入力コントローラを設定する必要があります。

セットアップ手順は、使用する入力コントローラのタイプによって異なります。Astra Control Centerは、多くの入力コントローラタイプをサポートしています。これらのセットアップ手順では、次の入力コントローラタイプの手順の例を示します。

* Istio入力
* nginx 入力コントローラ
* OpenShift 入力コントローラ


.必要なもの
* が必要です https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/["入力コントローラ"] すでに導入されている必要があります。
* 。 https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class["入力クラス"] 入力コントローラに対応するものがすでに作成されている必要があります。


.Istio Ingressの手順
. Istio Ingressを設定します。
+

NOTE: この手順 では、「デフォルト」の構成プロファイルを使用してIstioが導入されていることを前提としています。

. 入力ゲートウェイに必要な証明書と秘密鍵ファイルを収集または作成します。
+
CA署名証明書または自己署名証明書を使用できます。共通名はAstraアドレス（FQDN）である必要があります。

+
コマンド例：

+
[source, console]
----
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt
----
. シークレットを作成します `tls secret name` を入力します `kubernetes.io/tls` でTLS秘密鍵と証明書を使用する場合 `istio-system namespace` TLSシークレットで説明されているように、
+
コマンド例：

+
[source, console]
----
kubectl create secret tls [tls secret name] --key="tls.key" --cert="tls.crt" -n istio-system
----
+

TIP: シークレットの名前は、「istio-ingress.yaml」ファイルで指定されている「spec.tls.secretName`」と一致している必要があります。

. に入力リソースを配置します `netapp-acc` （またはカスタムネームスペース）。スキーマにはv1リソースタイプを使用します (`istio-Ingress.yaml` は次の例で使用されています）。
+
[listing]
----
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: istio
  tls:
  - hosts:
    - <ACC addess>
    secretName: [tls secret name]
  rules:
  - host: [ACC addess]
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80
----
. 変更を適用します。
+
[source, console]
----
kubectl apply -f istio-Ingress.yaml
----
. 入力のステータスを確認します。
+
[source, console]
----
kubectl get ingress -n [netapp-acc or custom namespace]
----
+
対応：

+
[listing]
----
NAME    CLASS HOSTS             ADDRESS         PORTS   AGE
ingress istio astra.example.com 172.16.103.248  80, 443 1h
----
. <<Astra Control Center を設定します,Astra Control Centerのインストールを完了します>>。


.Nginx Ingress Controller の手順
. タイプのシークレットを作成します `kubernetes.io/tls` でTLSの秘密鍵と証明書を使用する場合 `netapp-acc` （またはカスタム名前付き）ネームスペース。を参照してください https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets["TLS シークレット"]。
. 入力リソースをに配置します `netapp-acc` （またはカスタムネームスペース）。スキーマにはv1リソースタイプを使用します (`nginx-Ingress.yaml` は次の例で使用されています）。
+
[source, yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netapp-acc-ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: [class name for nginx controller]
  tls:
  - hosts:
    - <ACC address>
    secretName: [tls secret name]
  rules:
  - host: <ACC addess>
    http:
      paths:
        - path:
          backend:
            service:
              name: traefik
              port:
                number: 80
          pathType: ImplementationSpecific
----
. 変更を適用します。
+
[source, console]
----
kubectl apply -f nginx-Ingress.yaml
----



WARNING: nginxコントローラはデモセットではなく導入環境としてインストールすることを推奨します。

.OpenShift 入力コントローラの手順
. 証明書を調達し、 OpenShift ルートで使用できるようにキー、証明書、および CA ファイルを取得します。
. OpenShift ルートを作成します。
+
[source, console]
----
oc create route edge --service=traefik --port=web -n [netapp-acc or custom namespace] --insecure-policy=Redirect --hostname=<ACC address> --cert=cert.pem --key=key.pem
----




== Astra Control Center UI にログインします

Astra Control Center をインストールした後、デフォルトの管理者のパスワードを変更し、 Astra Control Center UI ダッシュボードにログインします。

.手順
. ブラウザでFQDNを入力します (`https://<FQDN>`）で使用しました `astraAddress` を参照してください `astra_control_center.yaml` CR When（時間） <<Astra Control Center を設定します,Astra Control Center をインストールした>>。
. プロンプトが表示されたら、自己署名証明書を承認します。
+

NOTE: カスタム証明書はログイン後に作成できます。

. Astra Control Centerのログインページで、に使用した値を入力します `email` インチ `astra_control_center.yaml` CR When（時間） <<Astra Control Center を設定します,Astra Control Center をインストールした>>をクリックし、次に初期セットアップパスワードを入力します (`ACC-[UUID]`）。
+

NOTE: 誤ったパスワードを 3 回入力すると、管理者アカウントは 15 分間ロックされます。

. [*Login*] を選択します。
. プロンプトが表示されたら、パスワードを変更します。
+

NOTE: 初めてログインしたときにパスワードを忘れ、他の管理ユーザアカウントがまだ作成されていない場合は、にお問い合わせください https://mysupport.netapp.com/site/["ネットアップサポート"] パスワード回復のサポートを受けるには、

. （オプション）既存の自己署名 TLS 証明書を削除して、に置き換えます link:../get-started/add-custom-tls-certificate.html["認証局（ CA ）が署名したカスタム TLS 証明書"]。




== インストールのトラブルシューティングを行います

いずれかのサービスのステータスが「 Error 」の場合は、ログを確認できます。400 ~ 500 の範囲の API 応答コードを検索します。これらは障害が発生した場所を示します。

.手順
. Astra Control Center のオペレータログを調べるには、次のように入力します。
+
[source, console]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----




== 次のステップ

* （オプション）お使いの環境に応じて、インストール後に実行します link:configure-after-install.html["設定手順"]。
* を実行して導入を完了します link:setup_overview.html["セットアップのタスク"]。

