---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。 
---
= 既知の問題
:hardbreaks:
:allow-uri-read: 
:source-highlighter: highlight.js
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。

現在のリリースに影響する既知の問題は次のとおりです。

* <<クラスタの管理後にボリュームnapshotclassを追加すると、アプリケーションのバックアップとSnapshotが失敗します>>
* <<kubeconfigファイルに複数のコンテキストが含まれている場合にAstra Control Centerでクラスタの管理が失敗する>>
* <<Astra Trident がオフラインの場合、 Internal Service Error （ 500 ）によりアプリケーションデータ管理処理が失敗する>>
* <<ONTAP NASエコノミーストレージクラスへのIn Placeリストア処理が失敗する>>
* <<Kerberos転送中暗号化を使用する場合にバックアップからのリストアが失敗することがある>>
* <<保持ポリシーの期限が切れたバケットでは、削除後もバックアップデータがバケットに残る>>




== クラスタの管理後にボリュームnapshotclassを追加すると、アプリケーションのバックアップとSnapshotが失敗します

でバックアップとSnapshotの作成が失敗する `UI 500 error` このシナリオでは、回避策 として、アプリリストを更新します。



== kubeconfigファイルに複数のコンテキストが含まれている場合にAstra Control Centerでクラスタの管理が失敗する

複数のクラスタおよびコンテキストで kubeconfig を使用することはできません。を参照してください link:https://kb.netapp.com/Cloud/Astra/Control/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["技術情報アーティクル"^] を参照してください。



== Astra Trident がオフラインの場合、 Internal Service Error （ 500 ）によりアプリケーションデータ管理処理が失敗する

アプリケーションクラスタの Astra Trident がオフラインになり（オンラインに戻った）、 500 件の内部サービスエラーが発生した場合に、アプリケーションデータ管理を試みると、アプリケーションクラスタ内のすべての Kubernetes ノードを再起動して機能を復旧します。



== ONTAP NASエコノミーストレージクラスへのIn Placeリストア処理が失敗する

アプリケーションのインプレースリストアを実行し（アプリケーションを元のネームスペースにリストア）、アプリケーションのストレージクラスで `ontap-nas-economy` ドライバの場合、スナップショットディレクトリが非表示になっていないとリストア処理が失敗することがあります。インプレースでリストアする前に、の手順に従ってください。 link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations["ONTAP NAS経済性に優れた運用向けのバックアップとリストアを実現"] Snapshotディレクトリを非表示にします。



== Kerberos転送中暗号化を使用する場合にバックアップからのリストアが失敗することがある

Kerberos転送中暗号化を使用しているストレージバックエンドにバックアップからアプリケーションをリストアすると、リストア処理が失敗することがあります。この問題は、Snapshotからのリストアや、NetApp SnapMirrorを使用したアプリケーションデータのレプリケートには影響しません。


NOTE: NFSv4ボリュームでKerberos転送中暗号化を使用する場合は、NFSv4ボリュームで正しい設定が使用されていることを確認してください。『NetApp NFSv4ドメイン設定』のセクション（13ページ）を参照してください。 https://www.netapp.com/media/16398-tr-3580.pdf["『NetApp NFSv4 Enhancements and Best Practices Guide』"^]。



== 保持ポリシーの期限が切れたバケットでは、削除後もバックアップデータがバケットに残る

バケットの保持ポリシーの期限が切れたあとにアプリケーションの変更不可のバックアップを削除すると、バックアップはバケットではなくAstra Controlから削除されます。この問題は今後のリリースで修正される予定です。



== 詳細については、こちらをご覧ください

* link:../release-notes/known-limitations.html["既知の制限"]

