---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。 
---
= 既知の問題
:hardbreaks:
:allow-uri-read: 
:source-highlighter: highlight.js
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。

現在のリリースに影響する既知の問題は次のとおりです。

* <<クラスタの管理後にボリュームnapshotclassを追加すると、アプリケーションのバックアップとSnapshotが失敗します>>
* <<ストレージクラスを設定してアプリケーションを導入すると、アプリケーションのクローンが失敗する>>
* <<kubeconfigファイルに複数のコンテキストが含まれている場合にAstra Control Centerでクラスタの管理が失敗する>>
* <<Istio環境で監視ポッドがクラッシュする可能性があります>>
* <<Astra Trident がオフラインの場合、 Internal Service Error （ 500 ）によりアプリケーションデータ管理処理が失敗する>>




== クラスタの管理後にボリュームnapshotclassを追加すると、アプリケーションのバックアップとSnapshotが失敗します

でバックアップとSnapshotの作成が失敗する `UI 500 error` このシナリオでは、回避策 として、アプリリストを更新します。



== ストレージクラスを設定してアプリケーションを導入すると、アプリケーションのクローンが失敗する

ストレージクラスを明示的に設定してアプリケーションを導入したあと（例： `helm install ...-set global.storageClass=netapp-cvs-perf-extreme`その後、アプリケーションのクローニングを実行するには、ターゲットクラスタに元のストレージクラスが指定されている必要があります。ストレージクラスを明示的に設定したアプリケーションを、同じストレージクラスを含まないクラスタにクローニングすると、失敗します。このシナリオではリカバリ手順はありません。



== kubeconfigファイルに複数のコンテキストが含まれている場合にAstra Control Centerでクラスタの管理が失敗する

複数のクラスタおよびコンテキストで kubeconfig を使用することはできません。を参照してください link:https://kb.netapp.com/Cloud/Astra/Control/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["技術情報アーティクル"^] を参照してください。



== Istio環境で監視ポッドがクラッシュする可能性があります

Istio環境でAstra Control CenterをCloud Insights とペアリングする場合は `telegraf-rs` ポッドがクラッシュすることがあります。回避策として、次の手順を実行します。

. クラッシュしたポッドを検索します。
+
[listing]
----
kubectl -n netapp-monitoring get pod | grep Error
----
+
次のような出力が表示されます。

+
[listing]
----
NAME READY STATUS RESTARTS AGE
telegraf-rs-fhhrh 1/2 Error 2 (26s ago) 32s
----
. クラッシュしたポッドを再起動し、交換します `<pod_name_from_output>` 影響を受けるポッドの名前を入力します。
+
[listing]
----
kubectl -n netapp-monitoring delete pod <pod_name_from_output>
----
+
次のような出力が表示されます。

+
[listing]
----
pod "telegraf-rs-fhhrh" deleted
----
. PODが再起動し、Error状態でないことを確認します。
+
[listing]
----
kubectl -n netapp-monitoring get pod
----
+
次のような出力が表示されます。

+
[listing]
----
NAME READY STATUS RESTARTS AGE
telegraf-rs-rrnsb 2/2 Running 0 11s
----




== Astra Trident がオフラインの場合、 Internal Service Error （ 500 ）によりアプリケーションデータ管理処理が失敗する

アプリケーションクラスタの Astra Trident がオフラインになり（オンラインに戻った）、 500 件の内部サービスエラーが発生した場合に、アプリケーションデータ管理を試みると、アプリケーションクラスタ内のすべての Kubernetes ノードを再起動して機能を復旧します。



== 詳細については、こちらをご覧ください

* link:../release-notes/known-limitations.html["既知の制限"]

