---
sidebar: sidebar 
permalink: release-notes/resolved-issues.html 
keywords: astra, control center, fixed bugs, fixes, resolved issues 
summary: 既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。 
---
= 解決済みの問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


このリリースの製品では、これらの問題が修正されています。



== 追加のバックアップはスケジュールされたバックアップの一部として保持されます

Astra Control Center の 1 つまたは複数のバックアップが、バックアップスケジュールで保持するように指定された数を超えて保持されることがあります。これらの追加バックアップは ' スケジュール・バックアップの一部として削除する必要がありますが ' 削除されず ' 保留状態になっています



== Astra Control Center で 10 進数の PVC を使用しているアプリケーションのバックアップまたはクローニングが失敗する

10 進数で作成したボリュームは、 Astra Control Center のバックアップまたはクローンプロセスを使用して失敗します。



== Astra Control Center UI では、永続的ボリュームの変更などのアプリケーションリソースの変更が表示されるまでに時間がかかります

データ保護処理（クローン、バックアップ、リストア）が完了して永続ボリュームのサイズを変更したあと、新しいボリュームのサイズが UI に表示されるまでに最大 20 分かかります。この UI の遅延は、アプリケーションリソースが追加または変更された場合にも発生する可能性があります。この場合、データ保護処理が数分以内に完了し、ストレージバックエンドの管理ソフトウェアを使用してボリュームサイズの変更を確認できます。



== インストール時に Astra Control Center カスタムリソース定義によって作成されたクラスタロールバインドが正しくない

このリリースでは、インストール中にクラスタロールを正しくバインドするためのパッチは不要になりました。



== ASUP の収集が生成中またはアップロード中の状態で停止します

ASUP ポッドが停止または再起動されると、 ASUP の収集が生成中またはアップロード中の状態で停止する可能性があります。



== オペレータが展開したアプリケーションと名前空間

展開する演算子とアプリケーションは、同じ名前空間を使用する必要があります。Astra Control では、 1 つのネームスペースにつき 1 つのオペレータが導入したアプリケーションのみがサポートされます



== 詳細については、こちらをご覧ください

* link:../release-notes/known-issues.html["既知の問題"]
* link:../release-notes/known-limitations.html["既知の制限"]
* link:../release-notes/known-issues-ads.html["Astra データストアのプレビューおよびこの Astra Control Center リリースでの既知の問題"]

